 ; ---------------------------------
;;              FOG
;; ---------------------------------
;; change RGB color of fog and density of fog

Weather

	HardwareFogColor = R:120 G:166 B:191          ;RGB values for the color & density of the fog
	HardwareFogEnable = Yes                       ;is there fog on this map?
	HardwareFogStart = 500                        ;distance that atmospheric fog begins. There is no fog closer than this value
	HardwareFogEnd = 2000                         ;distance that atmospheric fog reaches full effect
End

Weather
	
;; ---------------------------------
;;              SNOW
;; ---------------------------------
    SnowEnabled = Yes               ; enable/disable snow on the map.
    IsSnowing = Yes               ; is it snowing today?
    SnowTexture = EXSnowFlake2.tga
    SnowBoxHeight = 500             ; height from which snow falls
    SnowSpacing = 30             ; snow spacing -- less means more
    NumberTiles = 4

    SnowAmplitude = 20              ; amount of side-to-side movement. 
    SnowFrequencyScaleX = 0.01        ; speed of side-to-side wave movement.
    SnowFrequencyScaleY = 0.005         ; speed of side-to-side wave movement. 

    SnowPointSize = 0.75               ; scale the size of snow particles.
    SnowMinPointSize = 3           ; min point size
    SnowMaxPointSize = 8           ; max point size

    SnowPointSprites = No           ; set to "no" for point-sprite emulation.
    SnowQuadSize = 3               ; scale the size of snow particles when using point-sprite emulation.

    SnowSpeed = 50               ; speed at which snow falls
    SnowXYSpeed = X:40 Y:25

End

SpecialPower SpellBookHeal
	InitiateAtLocationSound 	= SpellHeal
	Enum                		= SPECIAL_SPELL_BOOK_HEAL
	Flags				= WATER_OK RESPECT_RECHARGE_TIME_DISCOUNT
	ReloadTime         		= 90000
	RequiredSciences     		= SCIENCE_Heal
	RadiusCursorRadius  		= SPELL_HEAL_RADIUS_CURSOR	
End