AIData
	LowLodTreeName = TreeLowLODHarlindon
END

Weather

    HardwareFogColor = R:000 G:100 B:200
    HardwareFogEnable = Yes
    HardwareFogStart = 600
    HardwareFogEnd = 1500

; ---------------------------------
;              SNOW
; ---------------------------------
    SnowEnabled = Yes               ; enable/disable snow on the map.
    IsSnowing = Yes               ; is it snowing today?
    SnowTexture = exsmokering.tga
    SnowBoxHeight = 900         ; height from which snow falls
    SnowSpacing = 30        ; snow spacing -- less means more
    NumberTiles = 4

    SnowAmplitude = 0 ; amount of side-to-side movement. 
    SnowFrequencyScaleX = 0        ; speed of side-to-side wave movement.
    SnowFrequencyScaleY = 0         ; speed of side-to-side wave movement. 

    SnowPointSize = 1               ; scale the size of snow particles.
    SnowMinPointSize = 2           ; min point size
    SnowMaxPointSize = 2           ; max point size

    SnowPointSprites = No           ; set to "no" for point-sprite emulation.
    SnowQuadSize = 2               ; scale the size of snow particles when using point-sprite emulation.

    SnowSpeed = -20             ; speed at which snow falls
    SnowXYSpeed = X:5 Y:5

End

Object WatcherHittingArm
RemoveModule ModuleTag_LifetimeUpdate
End

FXParticleSystem MAKOTombLight
  System
    Priority = HIGH_OR_ABOVE
    Shader = W3D_EMISSIVE
    Type = DRAWABLE
    ParticleName = exlight01.w3d
    Lifetime = 90 90
;    SystemLifetime = 30
    SortLevel = 1
    Size = 0.2 0.2
    BurstCount = 1 1
  End
  Color = DefaultColor
    Color1 = R:80 G:80 B:200 0 ; changed here
  End
  Alpha = DefaultAlpha
    Alpha2 = 0.2 0.2 10
    Alpha3 = 0 0 90
  End
  Update = DefaultUpdate
    SizeRate = 0.04 0.04
    SizeRateDamping = 0.99 0.99
    AngleZ = -50 50
    AngularDamping = 1 1
    Rotation = ROTATE_Z
  End
  Physics = DefaultPhysics
    VelocityDamping = 0.1 0.1
  End
  EmissionVelocity = OrthoEmissionVelocity
  End
  EmissionVolume = CylinderEmissionVolume
    Radius = 50
  End
  Draw = RenderObjectDraw
  End
End


FXParticleSystem SolasBubbles
  System
    Priority = HIGH_OR_ABOVE
    ParticleName = EXlightaura02.tga
    Lifetime = 90 90
;    SystemLifetime = 5
    Size = 10 20
    BurstDelay = 1 1
    BurstCount = 1 1
  End
  Color = DefaultColor
    Color1 = R:0 G:16 B:32 0
    Color2 = R:110 G:110 B:119 115
    Color3 = R:11 G:5 B:40 80
    ColorScale = -0.1 -1
  End
  Alpha = DefaultAlpha
    Alpha2 = 0.75 0.5 10
    Alpha3 = 0.15 0.2 20
    Alpha4 = 0 0 50
  End
  Update = DefaultUpdate
    SizeRate = 0.5 0.8
    SizeRateDamping = 0.7 0.99
    AngleZ = 0 10
    AngularDamping = 0.5 1
    Rotation = ROTATE_X
    AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    Gravity = -0.01
    VelocityDamping = 0.99 0.99
  End
  EmissionVelocity = OrthoEmissionVelocity
    Z = 2 4
  End
  EmissionVolume = CylinderEmissionVolume
    Radius = 9
    Offset = X:10 Y:-5 Z:-10
  End
  Draw = DefaultDraw
  End
End

FXParticleSystem MAKORedFoutainLight
  System
    Priority = HIGH_OR_ABOVE
    Shader = ALPHA
    ParticleName = EXMagma01.tga
    Lifetime = 80 80
;    SystemLifetime = 5
    Size = 40 60
    BurstDelay = 1 1
    BurstCount = 1 1
  End
  Color = DefaultColor
    Color1 = R:255 G:255 B:255 0
    Color2 = R:255 G:228 B:40 5
    Color3 = R:255 G:169 B:40 30
    Color4 = R:91 G:62 B:60 60
    ColorScale = -0.1 -1
  End
  Alpha = DefaultAlpha
    Alpha2 = 1 1 5
    Alpha3 = 1 1 20
    Alpha4 = 0 0 80
  End
  Update = DefaultUpdate
    SizeRate = 1 1.2
    SizeRateDamping = 0.7 0.99
    AngleZ = 0 10
    AngularDamping = 0.5 1
    Rotation = ROTATE_X
    AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    Gravity = -0.2
    VelocityDamping = 0.98 0.98
  End
  EmissionVelocity = OrthoEmissionVelocity
    Z = 2 9
  End
  EmissionVolume = CylinderEmissionVolume
    Radius = 5
    Offset = X:10 Y:-5 Z:-20
  End
  Draw = DefaultDraw
  End
End


Object CINE_ParticleSysProxy

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule
  Draw = W3DScriptedModelDraw ModuleTag_01New
    DefaultModelConditionState
      Model = NONE
		ParticleSysBone = NONE MAKOTombLight
    End    
    ModelConditionState = WORLD_BUILDER
			Model = locator		
	End
  End
END

  DisplayName      = OBJECT:Smoke
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes

End




Object CINE_ParticleSysProxy4

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule
  Draw = W3DScriptedModelDraw ModuleTag_01New
    DefaultModelConditionState
      Model = NONE
		ParticleSysBone = NONE MAKOBlueSmoke
    End    
    ModelConditionState = WORLD_BUILDER
			Model = locator		
	End
  End
END

  DisplayName      = OBJECT:Smoke
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes

End

Object CINE_ParticleSysProxy5

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule
  Draw = W3DScriptedModelDraw ModuleTag_01New
    DefaultModelConditionState
      Model = NONE
		ParticleSysBone = NONE SolasBubbles
    End    
    ModelConditionState = WORLD_BUILDER
			Model = locator		
	End
  End
END

  DisplayName      = OBJECT:Smoke
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes

End

Object CINE_ParticleSysProxy6

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule
  Draw = W3DScriptedModelDraw ModuleTag_01New
    DefaultModelConditionState
      Model = NONE
		ParticleSysBone = NONE MAKORedFoutainLight
    End    
    ModelConditionState = WORLD_BUILDER
			Model = locator		
	End
  End
END

  DisplayName      = OBJECT:Smoke
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes

End


FXParticleSystem MAKORedSmoke
  System
    Priority = HIGH_OR_ABOVE
    Shader = ALPHA
    ParticleName = EXSmokePuf07.tga
    Lifetime = 150 150
    Size = 40 60
    BurstDelay = 1 5
    BurstCount = 1 3
    IsEmitAboveGroundOnly = Yes
  End
  Color = DefaultColor
    Color1 = R:250 G:250 B:250 1
    Color2 = R:250 G:250 B:250 75
    Color3 = R:250 G:250 B:250 400
  End
  Alpha = DefaultAlpha
    Alpha1 = 0.15 0.15 100
    Alpha2 = 0.15 0.15 300
    Alpha3 = 0 0 400
  End
  Update = DefaultUpdate
    SizeRate = 1 2
    SizeRateDamping = 0.9 0.99
    AngleZ = 0 7
    AngularRateZ = -0.02 0.02
    AngularDamping = 1 1
    AngularDampingXY = 1 3
  End
  Physics = DefaultPhysics
    Gravity = 0.2
    VelocityDamping = 0.94 0.94
    DriftVelocity = X:1 Y:0.5 Z:0
  End
  EmissionVelocity = OrthoEmissionVelocity
    X = -0.4 -0.4
  End
  EmissionVolume = LineEmissionVolume
    IsHollow = Yes
    StartPoint = X:-2 Y:-2 Z:40
    EndPoint = X:3 Y:6 Z:100
  End
  Draw = DefaultDraw
  End
End

Object CINE_ParticleSysProxy2

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule
  Draw = W3DScriptedModelDraw ModuleTag_01New
    DefaultModelConditionState
      Model = NONE
		ParticleSysBone = NONE MAKORedSmoke
    End    
    ModelConditionState = WORLD_BUILDER
			Model = locator		
	End
  End
END

  DisplayName      = OBJECT:Smoke
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes

End

Object CINE_SunRays_Blue
	
	    ; *** ART Parameters ***
	AddModule
	  Draw = W3DScriptedModelDraw ModuleTag_New1
	    DefaultModelConditionState
	      Model = LM_Sunrays2
	    End
	  End
	
	  ; ***DESIGN parameters ***
	  DisplayName = OBJECT:SunRays
	  EditorSorting = SYSTEM
	  Browser = CINEMATICS SYSTEM
	
	  ; *** ENGINEERING Parameters ***
	  KindOf = SELECTABLE IMMOBILE
	  Shadow = NONE
	  Body = ActiveBody ModuleTag_new03
	    MaxHealth = 99999.0
	  End
	
	  Geometry = CYLINDER
	  GeometryMajorRadius = 13.6
	  GeometryMinorRadius = 12.0
	  GeometryHeight = 72.0
	  GeometryIsSmall = No
	End
End

PlayerTemplate FactionMen
Side						= Men
Evil	          = No
StartingUnit1 = NONE                      ;;;;;  So no starting builders
StartingUnit0 = NONE
StartingBuilding = NONE                   ;;;;;  No starting fortress. This will triger the instant defeat of the faction if you don't manualy plant another building for it on the map
BuildableHeroesMP			= CreateAHero
InitialUpgrades				= Upgrade_MenFaction
IntrinsicSciences			= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_MEN
	SpellBook					= GoodSpellBook
	SpellBookMp					= MenSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= MenSpellStoreCommandSet
End

PlayerTemplate FactionElves
Side						= Elves
Evil	          = No
StartingUnit1 = NONE
StartingUnit0 = NONE
StartingBuilding = NONE
BuildableHeroesMP			= CreateAHero
InitialUpgrades				= Upgrade_ElvesFaction
IntrinsicSciences			= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_ELVES
	SpellBook					= GoodSpellBook
	SpellBookMp					= ElvesSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= ElvesSpellStoreCommandSet
End

PlayerTemplate FactionDwarves
Side						= Dwarves
Evil	          = No
StartingUnit1 = NONE
StartingUnit0 = NONE
StartingBuilding = NONE
BuildableHeroesMP			= CreateAHero
InitialUpgrades				= Upgrade_DwarvesFaction
IntrinsicSciences			= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_DWARVES
	SpellBook					= GoodSpellBook
	SpellBookMp					= DwarvesSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= DwarvesSpellStoreCommandSet
End

PlayerTemplate FactionIsengard
Side						= Isengard
Evil	          = No
StartingUnit1 = NONE
StartingUnit0 = NONE
StartingBuilding = NONE
BuildableHeroesMP			= CreateAHero
InitialUpgrades				= Upgrade_IsengardFaction
IntrinsicSciences			= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_ISENGARD
	SpellBook					= EvilSpellBook
	SpellBookMp					= IsengardSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= IsengardSpellStoreCommandSet
End

PlayerTemplate FactionMordor
Side						= Mordor
Evil	          = No
StartingUnit1 = NONE
StartingUnit0 = NONE
StartingBuilding = NONE
BuildableHeroesMP			= CreateAHero
InitialUpgrades				= Upgrade_MordorFaction
IntrinsicSciences			= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_MORDOR
	SpellBook					= EvilSpellBook
	SpellBookMp					= MordorSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= MordorSpellStoreCommandSet
End

PlayerTemplate FactionWild
Side						= Wild
Evil	          = No
StartingUnit1 = NONE
StartingUnit0 = NONE
StartingBuilding = NONE
BuildableHeroesMP			= CreateAHero
InitialUpgrades				= Upgrade_WildFaction
IntrinsicSciences			= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_WILD
	SpellBook					= EvilSpellBook
	SpellBookMp					= WildSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= WildSpellStoreCommandSet
End

PlayerTemplate FactionAngmar
Side						= Angmar
Evil	          = No
StartingUnit1 = NONE
StartingUnit0 = NONE
StartingBuilding = NONE
BuildableHeroesMP			= CreateAHero
Evil	          = No
InitialUpgrades				= Upgrade_AngmarFaction
IntrinsicSciences			= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_ANGMAR
	SpellBook					= EvilSpellBook
	SpellBookMp					= AngmarSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= AngmarSpellStoreCommandSet
End

PlayerTemplate FactionCivilian            
	InitialUpgrades				= Upgrade_WildFaction Upgrade_GoblinDualEconomyChoice Upgrade_EvilDualEconomyChoice
	IntrinsicSciences			= SCIENCE_EVIL
	IntrinsicSciencesMP			= SCIENCE_EVIL
	SpellBook				= EvilSpellBook
	SpellBookMp				= EvilSpellBook
        PurchaseScienceCommandSetMP = EvilSpellStoreCommandSet                            
End

 Object WOR_GondorCastleBaseKeep
RemoveModule AutoDepositModuleTag
RemoveModule ModuleTag_NewMoneyDeadSpot
End

 Object MordorBalrog
RemoveModule ModuleTag_LifetimeUpdate
End

 Object AngmarShadeWolf
RemoveModule ModuleTag_LifetimeUpdate
End

 Object LesserWight
RemoveModule ModuleTag_LifetimeUpdate
End