;//////////////////////////////////////////////////////////////////////////////
;FILE: Rank.ini (SYSTEM) ////////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////////////

;This File is used to make the Powers's Point slower to get (from 60 to 100)

Rank 1
	SkillPointsNeededDefault		= 0	; If there is no side specific override (Replace Default with Side name, or with 'Campaign' for SP) just use this.
	SkillPointsNeededCampaign		= 0 
	SciencePurchasePointsGranted	= 5
End

Rank 2
	SkillPointsNeededDefault		= #MULTIPLY( 100 1 )
	SkillPointsNeededCampaign		= 100 ;400 - change to help Moria out in the solo experience.  11/04
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 3
	SkillPointsNeededDefault		= #MULTIPLY( 100 2 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 2 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 4
	SkillPointsNeededDefault		= #MULTIPLY( 100 3 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 3 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 5
	SkillPointsNeededDefault		= #MULTIPLY( 100 4 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 4 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 6
	SkillPointsNeededDefault		= #MULTIPLY( 100 5 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 5 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 7
	SkillPointsNeededDefault		= #MULTIPLY( 100 6 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 6 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 8
	SkillPointsNeededDefault		= #MULTIPLY( 100 7 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 7 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 9
	SkillPointsNeededDefault		= #MULTIPLY( 100 8 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 8 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 10
	SkillPointsNeededDefault		= #MULTIPLY( 100 9 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 9 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 11
	SkillPointsNeededDefault		= #MULTIPLY( 100 10 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 10 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 12
	SkillPointsNeededDefault		= #MULTIPLY( 100 11 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 11 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 13
	SkillPointsNeededDefault		= #MULTIPLY( 100 12 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 12 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 14
	SkillPointsNeededDefault		= #MULTIPLY( 100 13 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 13 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 15
	SkillPointsNeededDefault		= #MULTIPLY( 100 14 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 14 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 16
	SkillPointsNeededDefault		= #MULTIPLY( 100 15 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 15 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 17
	SkillPointsNeededDefault		= #MULTIPLY( 100 16 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 16 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 18
	SkillPointsNeededDefault		= #MULTIPLY( 100 17 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 17 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 19
	SkillPointsNeededDefault		= #MULTIPLY( 100 18 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 18 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 20
	SkillPointsNeededDefault		= #MULTIPLY( 100 19 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 19 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 21
	SkillPointsNeededDefault		= #MULTIPLY( 100 20 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 20 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 22
	SkillPointsNeededDefault		= #MULTIPLY( 100 21 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 21 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 23
	SkillPointsNeededDefault		= #MULTIPLY( 100 22 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 22 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 24
	SkillPointsNeededDefault		= #MULTIPLY( 100 23 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 23 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 25
	SkillPointsNeededDefault		= #MULTIPLY( 100 24 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 24 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 26
	SkillPointsNeededDefault		= #MULTIPLY( 100 25 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 25 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 27
	SkillPointsNeededDefault		= #MULTIPLY( 100 26 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 26 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 28
	SkillPointsNeededDefault		= #MULTIPLY( 100 27 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 27 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 29
	SkillPointsNeededDefault		= #MULTIPLY( 100 28 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 28 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 30
	SkillPointsNeededDefault		= #MULTIPLY( 100 29 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 29 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 31
	SkillPointsNeededDefault		= #MULTIPLY( 100 30 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 30 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 32
	SkillPointsNeededDefault		= #MULTIPLY( 100 31 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 31 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 33
	SkillPointsNeededDefault		= #MULTIPLY( 100 32 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 32 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 34
	SkillPointsNeededDefault		= #MULTIPLY( 100 33 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 33 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 35
	SkillPointsNeededDefault		= #MULTIPLY( 100 34 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 34 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 36
	SkillPointsNeededDefault		= #MULTIPLY( 100 35 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 35 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 37
	SkillPointsNeededDefault		= #MULTIPLY( 100 36 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 36 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 38
	SkillPointsNeededDefault		= #MULTIPLY( 100 37 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 37 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 39
	SkillPointsNeededDefault		= #MULTIPLY( 100 38 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 38 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 40
	SkillPointsNeededDefault		= #MULTIPLY( 100 39 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 39 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 41
	SkillPointsNeededDefault		= #MULTIPLY( 100 40 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 40 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 42
	SkillPointsNeededDefault		= #MULTIPLY( 100 41 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 41 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 43
	SkillPointsNeededDefault		= #MULTIPLY( 100 42 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 42 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 44
	SkillPointsNeededDefault		= #MULTIPLY( 100 43 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 43 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 45
	SkillPointsNeededDefault		= #MULTIPLY( 100 44 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 44 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 46
	SkillPointsNeededDefault		= #MULTIPLY( 100 45 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 45 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 47
	SkillPointsNeededDefault		= #MULTIPLY( 100 46 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 46 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 48
	SkillPointsNeededDefault		= #MULTIPLY( 100 47 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 47 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 49
	SkillPointsNeededDefault		= #MULTIPLY( 100 48 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 48 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 50
	SkillPointsNeededDefault		= #MULTIPLY( 100 49 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 49 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 51
	SkillPointsNeededDefault		= #MULTIPLY( 100 50 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 50 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 52
	SkillPointsNeededDefault		= #MULTIPLY( 100 51 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 51 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 53
	SkillPointsNeededDefault		= #MULTIPLY( 100 52 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 52 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 54
	SkillPointsNeededDefault		= #MULTIPLY( 100 53 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 53 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 55
	SkillPointsNeededDefault		= #MULTIPLY( 100 54 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 54 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 56
	SkillPointsNeededDefault		= #MULTIPLY( 100 55 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 55 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 57
	SkillPointsNeededDefault		= #MULTIPLY( 100 56 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 56 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 58
	SkillPointsNeededDefault		= #MULTIPLY( 100 57 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 57 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 59
	SkillPointsNeededDefault		= #MULTIPLY( 100 58 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 58 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 60
	SkillPointsNeededDefault		= #MULTIPLY( 100 59 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 59 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 61
	SkillPointsNeededDefault		= #MULTIPLY( 100 60 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 60 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 62
	SkillPointsNeededDefault		= #MULTIPLY( 100 61 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 61 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 63
	SkillPointsNeededDefault		= #MULTIPLY( 100 62 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 62 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 64
	SkillPointsNeededDefault		= #MULTIPLY( 100 63 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 63 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 65
	SkillPointsNeededDefault		= #MULTIPLY( 100 64 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 64 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 66
	SkillPointsNeededDefault		= #MULTIPLY( 100 65 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 65 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 67
	SkillPointsNeededDefault		= #MULTIPLY( 100 66 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 66 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 68
	SkillPointsNeededDefault		= #MULTIPLY( 100 67 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 67 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 69
	SkillPointsNeededDefault		= #MULTIPLY( 100 68 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 68 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 70
	SkillPointsNeededDefault		= #MULTIPLY( 100 69 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 69 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 71
	SkillPointsNeededDefault		= #MULTIPLY( 100 70 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 70 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 72
	SkillPointsNeededDefault		= #MULTIPLY( 100 71 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 71 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 73
	SkillPointsNeededDefault		= #MULTIPLY( 100 72 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 72 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 74
	SkillPointsNeededDefault		= #MULTIPLY( 100 73 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 73 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 75
	SkillPointsNeededDefault		= #MULTIPLY( 100 74 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 74 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 76
	SkillPointsNeededDefault		= #MULTIPLY( 100 75 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 75 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 77
	SkillPointsNeededDefault		= #MULTIPLY( 100 76 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 76 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 78
	SkillPointsNeededDefault		= #MULTIPLY( 100 77 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 77 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 79
	SkillPointsNeededDefault		= #MULTIPLY( 100 78 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 78 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 80
	SkillPointsNeededDefault		= #MULTIPLY( 100 79 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 79 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 81
	SkillPointsNeededDefault		= #MULTIPLY( 100 80 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 80 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 82
	SkillPointsNeededDefault		= #MULTIPLY( 100 81 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 81 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 83
	SkillPointsNeededDefault		= #MULTIPLY( 100 82 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 82 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 84
	SkillPointsNeededDefault		= #MULTIPLY( 100 83 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 83 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 85
	SkillPointsNeededDefault		= #MULTIPLY( 100 84 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 84 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 86
	SkillPointsNeededDefault		= #MULTIPLY( 100 85 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 85 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 87
	SkillPointsNeededDefault		= #MULTIPLY( 100 86 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 86 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 88
	SkillPointsNeededDefault		= #MULTIPLY( 100 87 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 87 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 89
	SkillPointsNeededDefault		= #MULTIPLY( 100 88 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 88 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 90
	SkillPointsNeededDefault		= #MULTIPLY( 100 89 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 89 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 91
	SkillPointsNeededDefault		= #MULTIPLY( 100 90 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 90 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 92
	SkillPointsNeededDefault		= #MULTIPLY( 100 91 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 91 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 93
	SkillPointsNeededDefault		= #MULTIPLY( 100 92 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 92 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 94
	SkillPointsNeededDefault		= #MULTIPLY( 100 93 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 93 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 95
	SkillPointsNeededDefault		= #MULTIPLY( 100 94 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 94 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 96
	SkillPointsNeededDefault		= #MULTIPLY( 100 95 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 95 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 97
	SkillPointsNeededDefault		= #MULTIPLY( 100 96 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 96 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 98
	SkillPointsNeededDefault		= #MULTIPLY( 100 97 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 97 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 99
	SkillPointsNeededDefault		= #MULTIPLY( 100 98 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 98 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 100
	SkillPointsNeededDefault		= #MULTIPLY( 100 99 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 99 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 101
	SkillPointsNeededDefault		= #MULTIPLY( 100 100 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 100 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 102
	SkillPointsNeededDefault		= #MULTIPLY( 100 101 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 101 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 103
	SkillPointsNeededDefault		= #MULTIPLY( 100 102 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 102 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 104
	SkillPointsNeededDefault		= #MULTIPLY( 100 103 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 103 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 105
	SkillPointsNeededDefault		= #MULTIPLY( 100 104 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 104 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 106
	SkillPointsNeededDefault		= #MULTIPLY( 100 105 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 105 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 107
	SkillPointsNeededDefault		= #MULTIPLY( 100 106 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 106 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 108
	SkillPointsNeededDefault		= #MULTIPLY( 100 107 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 107 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 109
	SkillPointsNeededDefault		= #MULTIPLY( 100 108 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 108 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 110
	SkillPointsNeededDefault		= #MULTIPLY( 100 109 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 109 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 111
	SkillPointsNeededDefault		= #MULTIPLY( 100 110 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 110 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 112
	SkillPointsNeededDefault		= #MULTIPLY( 100 111 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 111 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 113
	SkillPointsNeededDefault		= #MULTIPLY( 100 112 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 112 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 114
	SkillPointsNeededDefault		= #MULTIPLY( 100 113 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 113 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 115
	SkillPointsNeededDefault		= #MULTIPLY( 100 114 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 114 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 116
	SkillPointsNeededDefault		= #MULTIPLY( 100 115 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 115 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 117
	SkillPointsNeededDefault		= #MULTIPLY( 100 116 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 116 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 118
	SkillPointsNeededDefault		= #MULTIPLY( 100 117 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 117 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 119
	SkillPointsNeededDefault		= #MULTIPLY( 100 118 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 118 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 120
	SkillPointsNeededDefault		= #MULTIPLY( 100 119 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 119 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 121
	SkillPointsNeededDefault		= #MULTIPLY( 100 120 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 120 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 122
	SkillPointsNeededDefault		= #MULTIPLY( 100 121 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 121 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 123
	SkillPointsNeededDefault		= #MULTIPLY( 100 122 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 122 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End
   
Rank 124
	SkillPointsNeededDefault		= #MULTIPLY( 100 123 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 123 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 125
	SkillPointsNeededDefault		= #MULTIPLY( 100 124 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 124 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 126
	SkillPointsNeededDefault		= #MULTIPLY( 100 125 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 125 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 127
	SkillPointsNeededDefault		= #MULTIPLY( 100 126 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 126 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 128
	SkillPointsNeededDefault		= #MULTIPLY( 100 127 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 127 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 129
	SkillPointsNeededDefault		= #MULTIPLY( 100 128 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 128 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 130
	SkillPointsNeededDefault		= #MULTIPLY( 100 129 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 129 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 131
	SkillPointsNeededDefault		= #MULTIPLY( 100 130 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 130 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 132
	SkillPointsNeededDefault		= #MULTIPLY( 100 131 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 131 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 133
	SkillPointsNeededDefault		= #MULTIPLY( 100 132 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 132 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 134
	SkillPointsNeededDefault		= #MULTIPLY( 100 133 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 133 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 135
	SkillPointsNeededDefault		= #MULTIPLY( 100 134 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 134 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 136
	SkillPointsNeededDefault		= #MULTIPLY( 100 135 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 135 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 137
	SkillPointsNeededDefault		= #MULTIPLY( 100 136 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 136 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 138
	SkillPointsNeededDefault		= #MULTIPLY( 100 137 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 137 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 139
	SkillPointsNeededDefault		= #MULTIPLY( 100 138 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 138 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 140
	SkillPointsNeededDefault		= #MULTIPLY( 100 139 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 139 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 141
	SkillPointsNeededDefault		= #MULTIPLY( 100 140 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 140 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 142
	SkillPointsNeededDefault		= #MULTIPLY( 100 141 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 141 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 143
	SkillPointsNeededDefault		= #MULTIPLY( 100 142 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 142 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 144
	SkillPointsNeededDefault		= #MULTIPLY( 100 143 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 143 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 145
	SkillPointsNeededDefault		= #MULTIPLY( 100 144 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 144 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 146
	SkillPointsNeededDefault		= #MULTIPLY( 100 145 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 145 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End     

Rank 147
	SkillPointsNeededDefault		= #MULTIPLY( 100 146 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 146 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End
           
Rank 148
	SkillPointsNeededDefault		= #MULTIPLY( 100 147 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 147 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End     

Rank 149
	SkillPointsNeededDefault		= #MULTIPLY( 100 148 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 148 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 100
	SkillPointsNeededDefault		= #MULTIPLY( 100 149 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 149 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 151
	SkillPointsNeededDefault		= #MULTIPLY( 100 150 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 150 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 152
	SkillPointsNeededDefault		= #MULTIPLY( 100 151 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 151 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 153
	SkillPointsNeededDefault		= #MULTIPLY( 100 152 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 152 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 154
	SkillPointsNeededDefault		= #MULTIPLY( 100 153 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 153 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 155
	SkillPointsNeededDefault		= #MULTIPLY( 100 154 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 154 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 156
	SkillPointsNeededDefault		= #MULTIPLY( 100 155 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 155 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 157
	SkillPointsNeededDefault		= #MULTIPLY( 100 156 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 156 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 158
	SkillPointsNeededDefault		= #MULTIPLY( 100 157 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 157 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 159
	SkillPointsNeededDefault		= #MULTIPLY( 100 158 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 158 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End

Rank 160
	SkillPointsNeededDefault		= #MULTIPLY( 100 159 )
	SkillPointsNeededCampaign		= #MULTIPLY( PLAYER_SKILL_POINTS_DELTA_CAMPAIGN 159 )
	SciencePurchasePointsGranted	= PLAYER_PURCHASE_POINTS_GRANTED
End





