CommandButton Command_SelectRevivablesMenFortress
	Command                 = PUSH_VISIBLE_COMMAND_RANGE
	TextLabel               = CONTROLBAR:SelectRevivablesMenFortress
	ButtonImage             = UCCommon_GoodHeroes
	ButtonBorderType        = SYSTEM 
	DescriptLabel           = CONTROLBAR:ToolTipCommandSelectRevivablesMenFortress
	Radial                  = Yes
	CommandRangeStart		= 14
	CommandRangeCount		= 12
End

CommandSet MenFortress
	InitialVisible = 7
	//Main Menu
	1	= Command_ConstructMenPorter
	2   	= Command_SelectRevivablesMenFortress	
	3	= Command_SelectUpgradesMenFortress
	4	= Command_FireWeaponMenFortressBoilingOil
	5  	= Command_SpecialAbilityIvoryTowerVision
	6	= Command_Sell
	7   	= Command_EnableCEContentsMen

	//Upgrades Menu
	8	= Command_PurchaseUpgradeMenFortressBanners
	9	= Command_PurchaseUpgradeMenFortressHouseOfHealing
	10	= Command_PurchaseUpgradeMenFortressBoilingOil
	11	= Command_PurchaseUpgradeMenFortressFlamingMunitions
	12	= Command_PurchaseUpgradeMenFortressNumenorStonework
	13	= Command_PurchaseUpgradeMenFortressIvoryTower
	14	= Command_RadialBack

	//Hero Menu
	15	= Command_CreateAHeroReviveSlot
	16	= Command_GenericReviveSlot1 
	17	= Command_GenericReviveSlot2
	18	= Command_GenericReviveSlot3
	19	= Command_GenericReviveSlot4
	20	= Command_GenericReviveSlot5
	21	= Command_GenericReviveSlot6
	22	= Command_GenericReviveSlot7
	23	= Command_GenericReviveSlot8
	24	= Command_GenericReviveSlot9
	25	= Command_RadialBack		
End

Object MenFortressCitadel
CommandSet = MenFortress
AddModule
	Behavior = AttributeModifierAuraUpdate ModuleTag_PillageAura
		StartsActive	= Yes										; If no, requires upgrade to turn on.
		BonusName	= LurtzPassiveOutlawLeadership
		RefreshDelay	= 2000
		Range		= 999999
		AllowSelf	= Yes
		ObjectFilter	= ALL
	End
End
ReplaceModule ModuleTag_SlaughterMe
	Behavior = CitadelSlaughterHordeContain ModuleTag_SlaughterMeQuietly
		PassengerFilter				= GENERIC_FACTION_SLAUGHTERABLE
		ObjectStatusOfContained			= UNSELECTABLE ENCLOSED 
		CashBackPercent				= 0%		
		ContainMax				= 99	;// give it a huge capacity, just in case player sends his whole army in at once
		AllowEnemiesInside			= No
		AllowAlliesInside			= No
 		AllowNeutralInside			= No
 		AllowOwnPlayerInsideOverride		= Yes
		EnterSound				= GUI_RingReturned
		EntryOffset				= X:129.0 Y:0.0 Z:0.0
		EntryPosition				= X:100.0 Y:0.0 Z:0.0		// entry position needs to be offset from the root transform, otherwise fortress obscures point.
		
		ExitOffset				= X:129.0 Y:0.0 Z:0.0
		StatusForRingEntry			= HOLDING_THE_RING
		UpgradeForRingEntry			= Upgrade_RingHero Upgrade_FortressRingHero Upgrade_GondorFaction ;;,;; CE graphics fix
		ObjectToDestroyForRingEntry		= NONE +TheDroppedRing
		FXForRingEntry				= FX_OneRingFlare
	End
End
End

PlayerTemplate FactionMen
     StartingBuilding = MenFortress
     StartingUnit1 = NONE 
     StartingUnitOffset1 = X:20 Y:180 Z:0
     StartingUnit0 = NONE
     StartingUnitOffset0 = X:-20 Y:180 Z:0
     BuildableHeroesMP = CreateAHero
     PurchaseScienceCommandSetMP = SpellStoreAll
     SpellBookMp = SpellBookAll
End

Armor ToughHeroArmor
  Armor = DEFAULT          15%   
  Armor = SLASH            15%   
  Armor = PIERCE           15%   
  Armor = SPECIALIST       15%   
  Armor = CRUSH            10%   
  Armor = CAVALRY	   15% 
  Armor = SIEGE            25%   
  Armor = FLAME            25%   
  Armor = FROST            25%
  Armor = MAGIC            30%   ; 50%
  Armor = HERO             10%   ; 50%  
  Armor = HERO_RANGED      10%   ; 50%  
  Armor = POISON	   50% 
  Armor = STRUCTURAL	   50%

End

;;;;;;;;;;;;;;;;;;;;;;;;
;;;                  ;;;
;;;      GIMLI       ;;;
;;;                  ;;;
;;;;;;;;;;;;;;;;;;;;;;;;


Weapon RohanGimliAxe  ; BALANCE Gimli Axe Weapon
  LeechRangeWeapon      = Yes
  AttackRange           = STANDARD_MELEE_ATTACK_RANGE ;;,;; 20.0
  MeleeWeapon           = Yes
  WeaponSpeed           = 799999.2        ; dist/sec (huge value == effectively instant)
  DelayBetweenShots     = GIMLI_DELAYBETWEENSHOTS 	; time between shots, msec
  PreAttackDelay        = GIMLI_PREATTACKDELAY 	; 433 is natural time of the stabbing animation.
  PreAttackType         = PER_SHOT ; Do the delay each time we attack a new target
  FiringDuration        = GIMLI_FIRINGDURATION 		; min 600 for anim
  FireFX                = FX_GondorSwordHit

  DamageNugget
    Damage        = GIMLI_DAMAGE
    Radius        = 15.0
    DelayTime     = 0
    DamageType    = HERO
    DamageFXType  = SWORD_SLASH
    DeathType     = NORMAL
  End
End

Weapon Gimli202SuperAxe  ; BALANCE Gimli Axe Weapon
  LeechRangeWeapon      = Yes
  AttackRange           = STANDARD_MELEE_ATTACK_RANGE ; 20.0
  MeleeWeapon           = Yes
  WeaponSpeed           = 799999.2        ; dist/sec (huge value == effectively instant)
  DelayBetweenShots     = GIMLI_DELAYBETWEENSHOTS_SUPER 	; time between shots, msec
  PreAttackDelay        = GIMLI_PREATTACKDELAY_SUPER 	; 433 is natural time of the stabbing animation.
  PreAttackType         = PER_SHOT ; Do the delay each time we attack a new target
  FiringDuration        = GIMLI_FIRINGDURATION_SUPER 		; min 600 for anim
  FireFX                = FX_GondorSwordHit
  RadiusDamageAffects	= ENEMIES NEUTRALS NOT_SIMILAR ;;.;; Added for 2.02
	
	DamageNugget	;;.;; First swing
		Damage        		= GIMLI_DAMAGE_SUPER						
		Radius			= 18.0
		DamageArc 		= 180
		DelayTime		= 0
		DamageType		= HERO
		DamageFXType		= MAGIC
		DeathType		= EXPLODED
		DamageScalar		= 70% NONE +STRUCTURE	;;,;; 35%
	End
	MetaImpactNugget                    ; A Nugget that throws things back with force
		ShockWaveAmount		= 30
		ShockWaveRadius		= 18.0
		ShockWaveArc		= 180				; Should generally be equal to damage arc
		ShockWaveTaperOff	= 1.0
		DelayTime		= 0
	End
	
	DamageNugget	;;.;; Second swing
		Damage        		= GIMLI_DAMAGE_SUPER						
		Radius			= 18.0
		DamageArc 		= 180
		DelayTime		= 133
		DamageType		= HERO
		DamageFXType		= MAGIC
		DeathType		= EXPLODED
		DamageScalar		= 70% NONE +STRUCTURE
	End
	MetaImpactNugget                    ; A Nugget that throws things back with force
		ShockWaveAmount		= 30
		ShockWaveRadius		= 10.0
		ShockWaveArc		= 180				; Should generally be equal to damage arc
		ShockWaveTaperOff	= 1.0
		DelayTime		= 133
	End
End

Weapon GloinSmashWeapon
	IdleAfterFiringDelay = 0
	RadiusDamageAffects = ENEMIES ALLIES NOT_SIMILAR
	DelayBetweenShots = 5000               ; time between shots, msec
	PreAttackDelay        = 2600
	PreAttackType         = PER_ATTACK ; Do the delay each time we attack a new target
	PreAttackFX           = FX_GloinShatterPre
	FireFX                = FX_GloinShatterHammerBig ;,; FX_GloinShatterhammer
	FiringDuration      = 1400
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= GLOIN_SHATTERHAMMER_DAMAGE
		Radius			= 200
		DamageType		= MAGIC
		DamageFXType		= MAGIC
		DeathType		= EXPLODED
		DamageSpeed		= 700.0 ; must match the ShockWaveSpeed below
		DamageScalar		= 1% ANY ALLIES
	End
	MetaImpactNugget                    ; A Nugget that throws things back with force
		ShockWaveAmount   = 70.0
		ShockWaveRadius   = 200.0
		ShockWaveTaperOff = 1.0
		ShockWaveZMult    = 1.000
		ShockWaveSpeed	  = 700.0 
		SpecialObjectFilter	= ALL -MACHINE ;,;
	End
End

CommandButton Command_SpecialAbilitySlayer
	Command			= SPECIAL_POWER 
	SpecialPower		= SpecialAbilityGimliHeroMode
	TextLabel		= CONTROLBAR:Slayer
	ButtonImage		= HSGimliSlayer
	ButtonBorderType	= ACTION 
	DescriptLabel		= Describe:Slayer
	UnitSpecificSound	= GimliModeSlayerMS
	InPalantir		= Yes
	AutoAbility		= Yes
End

CommandButton Command_SpecialAbilityGloinSmash
  Command                 = SPECIAL_POWER 
  SpecialPower            = SpecialAbilityGloinSmash
  Options		  = NEED_TARGET_POS
  TextLabel               = CONTROLBAR:GloinSmash
  ButtonImage             = HSGloinShatterHammer
  RadiusCursorType	  = LeapRadiusCursor
  CursorName		  = Bombard
  InvalidCursorName       = GenericInvalid
  ButtonBorderType        = ACTION 
  DescriptLabel           = Describe:Smash
  InPalantir		  = Yes
  AutoAbility		  = Yes
End

CommandSet Gimli
	1	= Command_ToggleStance
	2  	= Command_GimliAxeThrow
	3  	= Command_RohanGimliLeap
	4 	= Command_SpecialAbilityDwarvenGloinShakeFoundation
	5  	= Command_SpecialAbilitySlayer
	6 	= Command_SpecialAbilityGloinSmash
	12 	= Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

Object DwarvenGimli
ShockwaveResistance = 34
CommandSet = Gimli
	;;;; SHAKE FOUNDATION SPECIAL ABILITY ;;;;--------------------------------------------------------------------
AddModule
	Behavior = UnpauseSpecialPowerUpgrade ModuleTag_ShakeFoundationEnabler
		SpecialPowerTemplate = SpecialAbilityDwarvenGloinShakeFoundation
		TriggeredBy = Upgrade_EnableDwarvenGloinShakeFoundation
	End
End
AddModule
	Behavior = SpecialPowerModule ModuleTag_ShakeFoundationStarter       
		SpecialPowerTemplate      = SpecialAbilityDwarvenGloinShakeFoundation
		UpdateModuleStartsAttack  = Yes
		StartsPaused		  = Yes
		InitiateSound		  = GloinVoiceGenericSpecialAbility
	End
End
AddModule
	Behavior = WeaponFireSpecialAbilityUpdate ModuleTag_ShakeFoundationWeaponFireUpdate
		SpecialPowerTemplate    = SpecialAbilityDwarvenGloinShakeFoundation
		SpecialWeapon			= DwarvenGloinShakeFoundationWeapon
		StartAbilityRange		= 15.0
		SkipContinue			= Yes
		UnpackTime				= 400		; Trigger on frame 42 (of 115)
		PackTime				= 1433		; Remaining 73 frames (of 115)
		MustFinishAbility		= Yes
	End
End
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_ShakeFoundationAutoAbility
		SpecialAbility			= SpecialAbilityDwarvenGloinShakeFoundation
		ForbiddenStatus = INSIDE_GARRISON ;;,;; This seems to prevent the ability from being used inside a tower
		Query					= 1 ANY ENEMIES +STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -UNATTACKABLE ;;,;; 1 ANY ENEMIES +STRUCTURE -UNATTACKABLE
		MaxScanRange			= 100
	End
End
	;;;; SHATTERHAMMER SPECIAL ABILITY ;;;;;;;;--------------------------------------------------------------------
AddModule
	Behavior = UnpauseSpecialPowerUpgrade ModuleTag_SmashEnabler
		SpecialPowerTemplate = SpecialAbilityGloinSmash
		TriggeredBy = Upgrade_EnableGloinSmash
	End
End
AddModule
	Behavior = SpecialPowerModule ModuleTag_SmashStarter       
		SpecialPowerTemplate      = SpecialAbilityGloinSmash
		UpdateModuleStartsAttack  = Yes
		StartsPaused		  	  = Yes
		InitiateSound				= GloinVoiceGenericSpecialAbility
	End
End
AddModule
	Behavior = WeaponFireSpecialAbilityUpdate ModuleTag_SmashWeaponFireUpdate   
		SpecialPowerTemplate    = SpecialAbilityGloinSmash
		SpecialWeapon			= GloinSmashWeapon
		WhichSpecialWeapon		= 2
		StartAbilityRange		= 10.0
		
		SkipContinue			= No
		UnpackTime			= 600		; Trigger on frame 60 (of 100)
		PackTime			= 300		; Remaining 40 frames (of 100)
		MustFinishAbility		= Yes
		BusyForDuration = 2000
	End
End
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_WoPAutoAbility ;;,;;
		SpecialAbility				= SpecialAbilityGloinSmash
		ForbiddenStatus = INSIDE_GARRISON ;;,;; This seems to prevent the ability from being used inside a tower
		MaxScanRange				= GLOIN_SMASH_WEAPON_RADIUS
		Query						= 75 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE ;,; 30
	End
End
ReplaceModule ModuleTag_SlayerEnabler
 	Behavior = UnpauseSpecialPowerUpgrade ModuleTag_SlayerEnablerAtLevel6
		SpecialPowerTemplate = SpecialAbilityGimliHeroMode
		TriggeredBy = Upgrade_EnableDwarvenGloinSlam
	End
End
ReplaceModule ModuleTag_GimliHealing
	Behavior = AutoHealBehavior ModuleTag_GimliHealing_FAST
		StartsActive = Yes
		HealingAmount = 100
		HealingDelay = 1000
		StartHealingDelay = HERO_HEAL_DELAY
		HealOnlyIfNotInCombat = Yes
	End
End
End

ExperienceLevel DwarvenGimliLevel4
	TargetNames					=	DwarvenGimli
	RequiredExperience			=	DWARVEN_GIMLI_REQUIRED_EXP_LEVEL_4
	ExperienceAward				=	DWARVEN_GIMLI_AWARD_LEVEL_4
	AttributeModifiers			=	DwarvenGimliBonusRank4 GenericHeroDamageBonusRank4
	Rank						=	4
	LevelUpFx					=	FX:GoodLevelUpFX
	Upgrades					=	Upgrade_EnableDwarvenGloinShakeFoundation
	SelectionDecal
		Texture					=	decal_hero_good
		Style					=	SHADOW_ALPHA_DECAL
		OpacityMin				=	50% 
		OpacityMax				=	100% 
		MinRadius				=	DWARVEN_GIMLI_DECAL_MIN_RADIUS
		MaxRadius				=	DWARVEN_GIMLI_DECAL_MAX_RADIUS
		MaxSelectedUnits		=	40
	End
END
ExperienceLevel DwarvenGimliLevel6
	TargetNames					=	DwarvenGimli
	RequiredExperience			=	DWARVEN_GIMLI_REQUIRED_EXP_LEVEL_6
	ExperienceAward				=	DWARVEN_GIMLI_AWARD_LEVEL_6
	AttributeModifiers			=	DwarvenGimliBonusRank6 GenericHeroDamageBonusRank6
	Rank						=	6
	LevelUpFx					=	FX:GoodLevelUpFX
	Upgrades					=	Upgrade_EnableDwarvenGloinSlam
	SelectionDecal
		Texture					=	decal_hero_good
		Style					=	SHADOW_ALPHA_DECAL
		OpacityMin				=	50% 
		OpacityMax				=	100% 
		MinRadius				=	DWARVEN_GIMLI_DECAL_MIN_RADIUS
		MaxRadius				=	DWARVEN_GIMLI_DECAL_MAX_RADIUS
		MaxSelectedUnits		=	40
	End
END
ExperienceLevel DwarvenGimliLevel10
	TargetNames					=	DwarvenGimli
	RequiredExperience			=	DWARVEN_GIMLI_REQUIRED_EXP_LEVEL_10
	ExperienceAward				=	DWARVEN_GIMLI_AWARD_LEVEL_10
	AttributeModifiers			=	DwarvenGimliBonusRank10 GenericHeroDamageBonusRank10
	Rank						=	10
	LevelUpFx					=	FX:GoodLevelUpFX
	Upgrades					=	Upgrade_EnableGloinSmash
	SelectionDecal
		Texture					=	decal_hero_good
		Style					=	SHADOW_ALPHA_DECAL
		OpacityMin				=	50% 
		OpacityMax				=	100% 
		MinRadius				=	DWARVEN_GIMLI_DECAL_MIN_RADIUS
		MaxRadius				=	DWARVEN_GIMLI_DECAL_MAX_RADIUS
		MaxSelectedUnits		=	40
	End
END

Object DwarvenGimli
CommandPoints = 0
	ReplaceModule ModuleTag_RespawnUpdate
		Behavior = RespawnUpdate ModuleTag_RespawnUpdate18
			DeathAnim			= DYING			;Model condition to play when killed-to-respawn
			DeathFX				= FX_GimliDieToRespawn	;FXList to play when killed-to-respawn
			DeathAnimationTime		= 4100			;How long DeathAnim will take.
			InitialSpawnFX			= FX_GimliInitialSpawn
			RespawnAnim			= LEVELED		;Animation to play when respawning.
			RespawnFX			= FX_GimliRespawn	;FXList to play when respawning.
			RespawnAnimationTime		= 2000			;Time it takes for respawn to play.
			AutoRespawnAtObjectFilter	= NONE +CASTLE_KEEP	;Respawn at this location -- and at it's exit production point if possible.
			ButtonImage			= HIGimli_res
			
			;RespawnEntries determine the ruleset for how a character can be revived. Some units may automatically respawn, others
			;may require a specific revive action performed on him. You can specify different values for each level... or use Level:Any
			RespawnRules =	AutoSpawn:No	Cost:3000		Time:16		Health:100%		;DEFAULT VALUES
			RespawnEntry =	Level:2		Cost:3100		Time:17					;For other levels, only override what is different.
			RespawnEntry =	Level:3		Cost:3300		Time:18
			RespawnEntry =	Level:4		Cost:3600		Time:19
			RespawnEntry =	Level:5		Cost:4000		Time:20
			RespawnEntry =	Level:6		Cost:4400		Time:21
			RespawnEntry =	Level:7		Cost:4800		Time:22
			RespawnEntry =	Level:8		Cost:5200		Time:23
			RespawnEntry =	Level:9		Cost:5600		Time:24
			RespawnEntry =	Level:10	Cost:6000		Time:25
		End
	End
	BountyValue = 3000
End

