
Upgrade Level1
Type = OBJECT
End


Object Monument01

  ; *** ART Parameters ***
Scale = 1.5

ReplaceModule  ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_New
    DefaultModelConditionState
      Model = CUElk_SKN
    End
  End
  End
KindOf          = STRUCTURE IMMOBILE UNATTACKABLE NOT_AUTOACQUIRABLE 
  

    AddModule
	Behavior = GrantUpgradeCreate ModuleTag_GrantMithrilMail
		UpgradeToGrant = Level1
	End
	End

	AddModule
	Behavior = SubObjectsUpgrade Costume_3
		TriggeredBy		= Level1 ; muwtchkng_mace.tga
		UpgradeTexture	= cuelkm.tga 0 MUAttkTroll_R.tga  ;mubalrogwingsash.tga  ;mubalrogwings.tga  ;mubalrogash.tga  ;fire.tga  ;
				RecolorHouse	= yES
	End


  Geometry = CYLINDER
  GeometryMajorRadius = 2.4
  GeometryMinorRadius = 2.4
  GeometryHeight = 4.8
  GeometryIsSmall = Yes
	End

End
  
Object CINE_ParticleSysProxy5

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule    ; ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01New
    DefaultModelConditionState
      Model = NONE
    End
    ModelConditionState = WORLD_BUILDER
            Model = locator
    End
  End
END

AddModule
Draw = W3DLightDraw ModuleTag_W3DLightDraw
    Ambient        = R:0 G:0 B:0        ;; Ambient Color...
    Diffuse        = R:160 G:200 B:0    ;; Diffusive Color...
    Radius        = 130            ;; Radius of Light.
    Intensity        = 1.8            ;; Intensity of light.
    FlickerAmplitude    = 0.5        ;; How strong it "flickers".
    FlickerFrequency    = 0.75        ;; How often it "flickers".
;    AttachToBoneInAnotherModule = Torch
End
END

  DisplayName      = OBJECT:Prop
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes
END


Object CINE_SunRays_Blue

AddModule
    ;  ART Parameters 
  Draw = W3DScriptedModelDraw ModuleTag_01
    DefaultModelConditionState
      Model = Sunrays_Blue
    End
  End

  ; DESIGN parameters 
  DisplayName = OBJECT:SunRaysBlue
  EditorSorting = SYSTEM
  Browser = CINEMATICS SYSTEM

  ;  ENGINEERING Parameters 
  KindOf = SELECTABLE IMMOBILE
  Shadow = NONE
  Body = ActiveBody ModuleTag_03
    MaxHealth = 99999.0
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 13.6
  GeometryMinorRadius = 12.0
  GeometryHeight = 72.0
  GeometryIsSmall = No
End
End