Weather
  HardwareFogColor = R:150 G:155 B:160
  HardwareFogEnable = Yes
  HardwareFogStart = 420
  HardwareFogEnd = 2000
End

Object MordorBalrog
 	RemoveModule ModuleTag_LifetimeUpdate

;	ReplaceModule ModuleTag_LifetimeUpdate
;	Behavior = LifetimeUpdate ModuleTag_Overider
;    		MinLifetime = 500000000
;    		MaxLifetime = 500000000
;  	End
; 	End
 
 ReplaceModule ModuleTag_02
  Body = ActiveBody ModuleTag_Overide
    MaxHealth = 22000                 
    MaxHealthDamaged = 11000
  End
 End
End

Object GondorTrebuchet
 ReplaceModule ModuleTag_02
  Body = ActiveBody ModuleTag_Overide
    MaxHealth = 3500                
  End
 End
End

Object SummonedDragon	
	ReplaceModule ModuleTag_Body
	Body = ActiveBody ModuleTag_Body1
		MaxHealth = 45000
	End
	End

	LocomotorSet
		Locomotor     = SummonedDragonLocomotor
		Condition     = SET_NORMAL
		Speed         = 70
	End

	RemoveModule ModuleTag_LifetimeUpdate
End

Object ElvenBattleTower
BuildCost = 400
BuildTime = 15
ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 80000
                End
	End
End

Object GondorBattleTower
BuildCost = 600
BuildTime = 25
ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 80000
                End
	End
End

Object DwarvenSentryTower
BuildCost = 600
BuildTime = 25
ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 80000
                End
	End
End

Object IsengardBattleTower
BuildCost = 600
BuildTime = 25
ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 80000
                End
	End
End

Object MordorBattleTower
BuildCost = 50
BuildTime = 15
ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 80000
                End
	End
End

Object WildSentryTower
BuildCost = 600
BuildTime = 25
ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 80000
                End
	End
End

SpecialPower SpecialAbilityThranduilDeadeye
	ReloadTime		= 50000
End

SpecialPower SpecialAbilityThornVengeance
 	ReloadTime         	= 60000
End

SpecialPower SpecialAbilityHawkStrike
	ReloadTime		= 20000
End

Armor NewDwarvenGuardianHeavyArmor
  Armor = DEFAULT          40%   ;  40%
  Armor = PIERCE           20%   ;
  Armor = FLAME            20%   ;   0%; ; 50
  Armor = MAGIC            15%   ; 100%; ; 50; ; 30
  Armor = HERO             70%   ;  50%
  Armor = HERO_RANGED      50%   ;
End

Object DwarvenGuardian
	ArmorSet
		Armor           = NewDwarvenGuardianHeavyArmor
	End
End

Armor NewPikemenHeavyArmor
  Armor = DEFAULT             30% ; 40%
  Armor = PIERCE              35% ;20%; ; 65
  Armor = FLAME               40% ;  0%; ; 50
  Armor = MAGIC               30% ;100%; ; 50
  Armor = HERO                50% ; 50%; ; 100
  Armor = HERO_RANGED         40%
End

Object IsengardPikeman
	ArmorSet
		Armor           = NewPikemenHeavyArmor	
	End
End

Object WildMarauder
	ArmorSet
		Armor           = NewWildMarauderHeavyArmor	
	End
End

Armor NewWildMarauderHeavyArmor
  Armor = DEFAULT             20% ;40%
  Armor = PIERCE              30% ;
  Armor = FLAME               25%  ; 0%; ; 50
  Armor = MAGIC               25% ;100%; ; 50
  Armor = HERO                50% ; 50%; ; 100
  Armor = HERO_RANGED         45% ;
End

Object MordorCorsairsOfUmbar
	ArmorSet
		Armor           = NewCorsairArmor
	End
End

Armor NewCorsairArmor
  Armor = DEFAULT         30%   ; 100%
  Armor = PIERCE          15%   ;
  Armor = FLAME           15% ; 100%
  Armor = MAGIC           15% ; 100%
  Armor = HERO            80%   ;
  Armor = HERO_RANGED     50% 
End

Object GondorTowerShieldGuard
	ArmorSet
		Armor		= NewTowerGuardHeavyArmor
	End
End

Object GondorTrebuchet
	ArmorSet
		Armor   	= NewSiegeEngineArmor
	End
End

Armor NewTowerGuardHeavyArmor
  Armor = DEFAULT             20%
  Armor = PIERCE              25%
  Armor = FLAME               20% ;  0%
  Armor = MAGIC               20% ;100%
  Armor = HERO                30% ; 50%; ; 100
  Armor = HERO_RANGED         25%
End

Armor NewSiegeEngineArmor
  Armor = DEFAULT          5%   
  Armor = PIERCE           1% 
  Armor = FLAME            5%   ; ; 100
  Armor = MAGIC            5%   ; ; 100
  Armor = HERO            20%   
  Armor = HERO_RANGED      1%
End

Object DwarvenPhalanx
	ArmorSet
		Armor           = NewDwarvenPikemenHeavyArmor	
	End
End

Armor NewDwarvenPikemenHeavyArmor
  Armor = DEFAULT             20% ; 40%
  Armor = PIERCE              20%
  Armor = FLAME               25% ;  0%; ; 50
  Armor = MAGIC               25% ;100%; ; 50
  Armor = HERO                30% ; 50%; ; 100
  Armor = HERO_RANGED         25%
End

Object IsengardFighter
	ArmorSet
		Armor		= NewUrukHaiHeavyArmor
	End
End

Armor NewUrukHaiHeavyArmor
  Armor = DEFAULT             20% ; 40%
  Armor = PIERCE              15% ;
  Armor = FLAME               10% ;  0%; ; 50
  Armor = MAGIC               10% ;100%; ; 50; ; 30
  Armor = HERO                40% ; 50%
  Armor = HERO_RANGED         30% 
End

Object GoblinSpiderRider
	ArmorSet
		Armor           = NewWildSpiderRiderArmor
	End
End

Armor NewWildSpiderRiderArmor
  Armor = DEFAULT         30%
  Armor = PIERCE          15%;
  Armor = FLAME           15%   ;  30%; ; 100
  Armor = MAGIC           10%   ;; ; 100
  Armor = HERO            80%   ;
  Armor = HERO_RANGED     70% 
End

Object MordorEasterling
	ArmorSet
		Armor		= NewRhunHeavyArmor
	End
End

Armor NewRhunHeavyArmor
  Armor = DEFAULT         20%
  Armor = PIERCE          20% 
  Armor = FLAME           20%   ;  30%; ; 100
  Armor = MAGIC           20%   ;; ; 100
  Armor = HERO            30%   ;; ; 200
  Armor = HERO_RANGED     30%
End

Armor NewMumakilArmor
  Armor = DEFAULT        20%
  Armor = PIERCE         35%
  Armor = HERO		 75%    ; ; 200
  Armor = MAGIC		 20%    ; ; 100
  Armor = HERO_RANGED    80% ; ; 100
  Armor = FLAME          35%
End

Object MordorMumakil
	ArmorSet
		Armor           = NewMumakilArmor
	End
End

Object ElvenLorienWarrior
	ArmorSet
		Armor           = NewLorienSoldierHeavyArmor
	End
End

Armor NewLorienSoldierHeavyArmor
  Armor = DEFAULT             20% ;
  Armor = PIERCE              10% ;
  Armor = FLAME               10% ;  0%;
  Armor = MAGIC                6% ;100%
  Armor = HERO                40% ; 50%
  Armor = HERO_RANGED         35% ;
End

Object RohanRohirrim
	ArmorSet
		Armor		= NewRohirrimHeavyArmor
	End
End

Armor NewRohirrimHeavyArmor
  Armor = DEFAULT            	30% 
  Armor = PIERCE              	 8% ; 
  Armor = FLAME               	30% ; ; 50; ; 75
  Armor = MAGIC              	25% ; ; 50
  Armor = HERO               	60% 
  Armor = HERO_RANGED         	50% 
End

Object IsengardWargRider
	ArmorSet
		Armor           = NewWargHeavyArmor	
	End
End

Armor NewWargHeavyArmor
  Armor = DEFAULT         30%   ; 100%
  Armor = PIERCE          15% 
  Armor = FLAME           20%   ;  30%; ; 50
  Armor = MAGIC           20%   ;; ; 50
  Armor = HERO            60%
End