


Object MordorSauron	
	RemoveModule ModuleTag_SauronDarkness
End


Object WatcherHead
	RemoveModule ModuleTag_LifetimeUpdate
ReplaceModule ModuleTag_Body
	Body = ActiveBody ModuleTag_Overide
		MaxHealth = 15000
		End
	End
End

Object WatcherHittingArm	
	RemoveModule ModuleTag_LifetimeUpdate
End

Object WatcherCaldera
	RemoveModule ModuleTag_LifetimeUpdate
End

Object Wyrm
	RemoveModule ModuleTag_LifetimeUpdate
ReplaceModule ModuleTag_Body
	Body = ActiveBody ModuleTag_Overide
		MaxHealth = 20000
		End
	End
End

Armor NewBalrogArmor
  Armor = DEFAULT		3%     ;this sets the level for all nonspecified damage types
  Armor = CRUSH			6%     ;horseman damage
  Armor = SLASH			6%     ;soldier damage
  Armor = URUK			6%     ;soldier damage
  Armor = PIERCE		3%     ;archer damage
  Armor = SIEGE			8%     ;siege damage
  Armor = STRUCTURAL		8%	;Structural damage (Ent rocks)
  Armor = HERO			100%    ;hero damage
  Armor = MAGIC			9%     ;magic damage
  Armor = HERO_RANGED		80%    ;Hero bow damage   
End

Object MordorBalrog
	RemoveModule ModuleTag_LifetimeUpdate
	ArmorSet
		Armor           = NewBalrogArmor
		DamageFX        = FellBeastDamageFX
	End
End
 	
Object AngmarShadeWolf
	RemoveModule ModuleTag_LifetimeUpdate
End

Object SummonedDragon
	LocomotorSet
		Locomotor     = SummonedDragonLocomotor
		Condition     = SET_NORMAL
		Speed         = 60
	End

	RemoveModule ModuleTag_LifetimeUpdate

	ArmorSet
		Conditions      = None
		Armor           = NewSummonedDragonArmor
		DamageFX        = FellBeastDamageFX
	End
End

Object ElvenMirrorOfGaladriel
   ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 7500
                End
	End

End

;----------------------------------------------------

Object IsengardBallista
CommandPoints = 60
BuildTime = 200
MaxSimultaneousOfType = 2
End

Object GondorTrebuchet
CommandPoints = 60
BuildTime = 200
MaxSimultaneousOfType = 2
End

Object MordorCatapult
CommandPoints = 60
BuildCost = 800
BuildTime = 240
MaxSimultaneousOfType = 2
End

Object DwarvenCatapult
CommandPoints = 60
BuildTime = 200
MaxSimultaneousOfType = 2
End

;----------------------------------------------------

Object ElvenBattleTower
BuildCost = 400
BuildTime = 30
End

Object GondorBattleTower
BuildCost = 400
BuildTime = 40
End

Object DwarvenSentryTower
BuildCost = 400
BuildTime = 30
End

Object IsengardBattleTower
BuildCost = 400
BuildTime = 20
End

Object MordorBattleTower
BuildCost = 200
BuildTime = 15
End

Object WildSentryTower
BuildCost = 400
BuildTime = 20
End

Object AngmarSentryTower
BuildCost = 400
BuildTime = 20
End

;----------------------------------------------------

Object RohanElvenWarriorHorde
BuildTime = 20
BuildCost = 500
MaxSimultaneousOfType = 6
End

Object RohanHobbitFriendsHordeInn
BuildTime = 15
BuildCost = 150
MaxSimultaneousOfType = 8
End

Object RohanPeasantHorde
BuildTime = 10
BuildCost = 50
MaxSimultaneousOfType = 10
End

Object MordorHaradrimLancerHorde
BuildTime = 10
BuildCost = 50
MaxSimultaneousOfType = 10
End

Object GoblinsWildmanHordeInn
BuildTime = 25
BuildCost = 300
MaxSimultaneousOfType = 8
End

Object IsengardCorsairsOfUmbarHordeInn
BuildTime = 200
BuildCost = 800
MaxSimultaneousOfType = 2
End

;----------------------------------------------------

Object MordorCorsairsOfUmbarHorde
BuildTime = 200
BuildCost = 800
MaxSimultaneousOfType = 2
End

Object MordorOrcPit
BuildTime = 20
BuildCost = 100
End

Object MordorFighterHorde
BuildTime = 15
End

Object MordorArcherHorde
BuildTime = 20
BuildCost = 100
End

Object HaradrimPalace
BuildTime = 20
BuildCost = 200
End

Object MordorEasterlingHorde
BuildTime = 20
BuildCost = 300
End

Object MordorHaradrimArcherHorde
BuildTime = 15
BuildCost = 200
End

Object MordorMumakil
BuildCost = 600
End

Object MordorTavern
BuildCost = 300
End

Object MordorTrollCage
BuildCost = 300
End

Object MordorMumakilPen
BuildCost = 400
End

;----------------------------------------------------

Object DwarvenSiegeWorks
BuildCost = 750
BuildTime = 20
End

Object DwarvenArcheryRange
BuildCost = 500
End

Object DwarvenMenOfDaleHorde
BuildCost = 500
BuildTime = 30
End

Object DwarvenAxeThrowerHorde
BuildCost = 250
BuildTime = 25
End

Object DwarvenPhalanxHorde
BuildCost = 300
BuildTime = 30
End

Object DwarvenGuardianHorde
BuildCost = 300
End

;----------------------------------------------------

Object ElvenMithlondSentryHorde
BuildCost = 300
BuildTime = 20
End

Object ElvenLorienWarriorHorde
BuildCost = 300
BuildTime = 30
End

Object EregionForge
BuildCost = 750
End

Object ElvenMirkwoodArcherHorde
BuildCost = 500
BuildTime = 30
End

;----------------------------------------------------

Object GoblinFissure
BuildTime = 40
BuildCost = 400
End

Object WildTreasureTrove
BuildCost = 750
BuildTime = 20
End

Object WildMarauderHorde
BuildCost = 300
BuildTime = 15
End

Object GoblinCave
BuildCost = 300
BuildTime = 20
End

Object GoblinArcherHorde
BuildCost = 80
BuildTime = 20
End

Object GoblinFighterHorde
BuildCost = 60
BuildTime = 15
End

Object WildSpiderPit
BuildCost = 300
BuildTime = 20
End

Object WildSpiderlingHorde
BuildCost = 200
BuildTime = 15
End

Object GoblinSpiderRiderHorde
BuildCost = 400
End

;----------------------------------------------------

Object GondorBarracks
BuildTime = 30
BuildCost = 300
End

Object GondorRangerHorde
BuildCost = 500
BuildTime = 30
End

Object GondorTowerShieldGuardHorde
BuildCost = 300
BuildTime = 20
End

Object GondorFighterHorde
BuildCost = 250
End

;----------------------------------------------------

Object IsengardPikemanHorde
BuildCost = 300
BuildTime = 30
End

Object IsengardUrukCrossBowHorde
BuildCost = 400
BuildTime = 40
End

;----------------------------------------------------

Object AngmarDen
BuildTime = 30
BuildCost = 400
End

Object AngmarRangerHorde
BuildCost = 500
BuildTime = 30
End

Object AngmarHillTrollHorde
BuildCost = 400
BuildTime = 20
End
