
PlayerTemplate FactionCivilian  ; makes ai able to fire spells
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
End


PlayerTemplate FactionMen
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
End

PlayerTemplate FactionElves
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
End

PlayerTemplate FactionDwarves
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
End

PlayerTemplate FactionIsengard
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
End



PlayerTemplate FactionWild
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
End

PlayerTemplate FactionMordor
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
End

PlayerTemplate FactionAngmar
IntrinsicSciencesMP = SCIENCE_EVIL SCIENCE_GOOD
PurchaseScienceCommandSetMP = FortressDefenseSpellStoreCommandSet
SpellBookMp = FortressDefenseSpellBook
End

;===============for the spellbook

Science SCIENCE_Fury
PrerequisiteSciences = SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_Lottery
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_ElvenWood
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
  SciencePurchasePointCost = 1
  SciencePurchasePointCostMP = 1
  IsGrantable = Yes
End

Science SCIENCE_EagleAllies
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_WatcherAlly
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_Snowbind
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_ArmyOfTheDead
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_Flood
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_Earthquake
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_SummonBalrog
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_Undermine
PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
SciencePurchasePointCost = 1
SciencePurchasePointCostMP = 1
IsGrantable = Yes
End

Science SCIENCE_PalantirVision
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
  SciencePurchasePointCost = 1
  SciencePurchasePointCostMP = 1
  IsGrantable = Yes
End

Science SCIENCE_FreezingRain
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
  SciencePurchasePointCost = 1
  SciencePurchasePointCostMP = 1
  IsGrantable = Yes
End

Science SCIENCE_Bombard
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_EVIL
  SciencePurchasePointCost = 1
  SciencePurchasePointCostMP = 1
  IsGrantable = Yes
End

SpecialPower SpellBookElvenWood
	Enum				= SPECIAL_SPELL_BOOK_ELVEN_WOOD
	RadiusCursorRadius		= SPELLBOOK_TAINT_RADIUS
	RequiredSciences		= SCIENCE_ElvenWood
	ReloadTime      		= 240000 ; in milliseconds
	InitiateAtLocationSound 	= SpellElvenWood
	ViewObjectDuration 		= 5000
	ViewObjectRange 		= SPELLBOOK_TAINT_RADIUS
	Flags				= NO_FORBIDDEN_OBJECTS RESPECT_RECHARGE_TIME_DISCOUNT
	ForbiddenObjectFilter		= NONE +WatcherHead +WatcherHittingArm +WatcherCaldera
	ForbiddenObjectRange		= SPELLBOOK_TAINT_RADIUS
End

SpecialPower SpellBookFury
	Enum				= SPECIAL_SPELL_BOOK_FUEL_THE_FIRES
	RequiredSciences		= SCIENCE_Fury
	ReloadTime      		= 520000 ; in milliseconds

End

SpecialPower SpellBookEagleAllies
	Enum			= SPECIAL_SPELL_BOOK_EAGLE_ALLIES
	Flags					= WATER_OK RESPECT_RECHARGE_TIME_DISCOUNT
	RequiredSciences		= SCIENCE_EagleAllies
	ReloadTime      	= SPELL_RECHARGE_TIME_TIER_3 ; in milliseconds
	InitiateAtLocationSound = SpellEagleAlliesSummon	;EagleVoiceSelect
	RadiusCursorRadius	= 100.0
End

SpecialPower SpellBookSnowbind
	Enum				= SPECIAL_SPELL_BOOK_SNOWBIND
	RadiusCursorRadius		= 50			; Match the radius in FXList TaintFX
	RequiredSciences		= SCIENCE_Snowbind
	ReloadTime			= SPELL_RECHARGE_TIME_TIER_1		; in milliseconds
	InitiateAtLocationSound = SnowbindMS
	ViewObjectDuration		= 5000
	ViewObjectRange			= 175
	Flags			= NEEDS_OBJECT_FILTER RESPECT_RECHARGE_TIME_DISCOUNT
	ObjectFilter		= ANY ENEMIES NEUTRAL ALLIES +STRUCTURE
End

SpecialPower SpellBookLottery
	Enum				= SPECIAL_SPELL_BOOK_EYE_OF_SAURON
	RequiredSciences		= SCIENCE_Lottery
	ReloadTime      		= 300000 ; in milliseconds

End

SpecialPower SpellBookFreezingRain
  Enum              = SPECIAL_SPELL_BOOK_FREEZING_RAIN
  RequiredSciences   = SCIENCE_FreezingRain
  ReloadTime        = SPELL_RECHARGE_TIME_TIER_3
  InitiateSound     = ThunderStrikesStereo
  Flags				= RESPECT_RECHARGE_TIME_DISCOUNT
End

SpecialPower SpellBookBombard
	Enum				= SPECIAL_SPELL_BOOK_BOMBARD
	Flags				= WATER_OK RESPECT_RECHARGE_TIME_DISCOUNT
	RadiusCursorRadius		= 200
	RequiredSciences  		= SCIENCE_Bombard
	ReloadTime       		= SPELL_RECHARGE_TIME_TIER_3
	InitiateAtLocationSound		= SpellBarrageStartMS
End

ModifierList FuryBonus
	Category = LEVEL
	Modifier = DAMAGE_MULT    200% ; +100% damage
	Duration = 45000	        ; 45s			
End

CommandButton Command_SpellBookCalltheHorde          ;fury
	Command				= SPELL_BOOK
	SpecialPower		= SpellBookFury
	TextLabel			= CONTROLBAR:SoSBonus
	DescriptLabel		= CONTROLBAR:TooltipSoSBonus   
	ButtonImage			= SBEvil_CalltheHorde
	Options			= CANCELABLE
	ButtonBorderType   	= ACTION  ;UPGRADE
	InPalantir		= Yes
	Radial			= No
  UnitSpecificSound			= CaH_BerserkerRage
End


CommandButton Command_LurtzPillage                 ;lottery
  Command                 = SPELL_BOOK
  SpecialPower            = SpellBookLottery
	TextLabel			= CONTROLBAR:Lottery
	DescriptLabel		= CONTROLBAR:TooltipLottery
	ButtonImage			= HSBalrogIgnite
	Options			= CANCELABLE
	ButtonBorderType   	= ACTION  ;UPGRADE
	InPalantir		= Yes
	Radial			= No
  UnitSpecificSound			= GUI_GollumHappy
End


CommandSet FortressDefenseSpellBookCommandSet
	1 = Command_SpellBookElvenGifts
        2 = Command_SpellBookHeal
        3 = Command_SpellBookElvenWood
        4 = Command_SpellBookCalltheHorde
        5 = Command_SpellBookWarChant
        6 = Command_LurtzPillage
        7 = Command_SpellBookBombard
        8 = Command_SpellBookSnowbind
	9 = Command_SpellBookEagleAllies
       10 = Command_SpellBookFlood
       11 = Command_SpellBookBalrogAlly
       12 = Command_SpellBookArmyoftheDead
End

CommandSet FortressDefenseSpellStoreCommandSet ; this is generic, don't try to activate the spellstore (remove the script), or you will get GAMEDAT.error
	1 = Command_PurchaseSpellHeal
        
End


Object FortressDefenseSpellBook
CommandSet          = FortressDefenseSpellBookCommandSet
RadarPriority       = NOT_ON_RADAR
KindOf              = SPELL_BOOK IMMOBILE IGNORES_SELECT_ALL INERT



   AddModule 
	Behavior = SpecialPowerModule		SpellBookLottery_ModuleTag
		SpecialPowerTemplate		= SpellBookLottery
		UpdateModuleStartsAttack	= No
		AffectAllies			= No ; Should not try to affect ally units
		AvailableAtStart		= No
		RequirementsFilterMPSkirmish	= SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic	= SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
   END

AddModule
	Behavior = OCLSpecialPower ModuleTag_Undermine
		SpecialPowerTemplate = SpellBookUndermine
		OCL                  = OCL_SpellBookUndermine
		CreateLocation       = CREATE_AT_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = OCLSpecialPower ModuleTag_Earthquake
		SpecialPowerTemplate = SpellBookEarthquake
		OCL                  = OCL_SpellBookEarthquake
        ;TriggerFX			 = FX_ElvenAlliesSummon
		CreateLocation       = CREATE_AT_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior				 = OCLSpecialPower ModuleTag_PalantirVision
		SpecialPowerTemplate = SpellBookPalantirVision
		OCL                  = SpecialPowerPalantirVision
		CreateLocation       = CREATE_AT_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = OCLSpecialPower ModuleTag_SummonEagles
		SpecialPowerTemplate = SpellBookEagleAllies
		OCL                  = OCL_SpawnEagles
		CreateLocation       = CREATE_ABOVE_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = FreezingRainSpecialPower ModuleTag_FreezingRain
		SpecialPowerTemplate			= SpellBookFreezingRain
		AttributeModifierAffects		= ALL ENEMIES
		AntiCategory					= LEADERSHIP
		AntiFX							= FX_AntiLeadership ; FX for anti category
		AttributeModifierWeatherBased	= Yes
		WeatherDuration					= SPELL_FREEZINGRAIN_DURATION
		ChangeWeather					= RAINY
		AvailableAtStart				= No
		BurnRateModifier				= -100
		BurnDecayModifier				= 20
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = SpecialPowerModule		SpellBookWarChant_ModuleTag
		SpecialPowerTemplate		= SpellBookWarChant
		AttributeModifier			= SpellBookWarChant
		AttributeModifierRange		= 110
		AttributeModifierAffects	= ANY +INFANTRY +CAVALRY +MACHINE -IMMOBILE -DOZER +HERO -STRUCTURE -BASE_FOUNDATION -HORDE +DwarvenBattleWagon -RohanOathbreaker -MordorRamCrew +MordorWorker -IsengardRamCrew +IsengardBeserker
		TriggerFX					= FX_SpellWarChant
		UpdateModuleStartsAttack	= No
		AvailableAtStart			= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = SpecialPowerModule ModuleTag_RallyingCall
		SpecialPowerTemplate		= SpellBookRallyingCall
		AttributeModifier			= SpellBookRallyingCallModifier
		AttributeModifierRange		= 100
		AttributeModifierAffects	= GENERIC_BUFF_RECIPIENT_OBJECT_FILTER ;;,;; ANY +HORDE +INFANTRY -HERO -MordorBlackRiderHorde -MordorBlackRider -GondorKnightsofDol -GondorKnightsofDolHorde -IsengardFanatic -IsengardBerserkerHorde  -DwarvenZerker -DwarvenZerkerHorde -NoldorWarrior -NoldorWarriorHorde -WildBabyDrakeHorde -WildBabyDrake ;;.;; Added rest of MHH
		TriggerFX					= FX_SpellRallyingCall
		UpdateModuleStartsAttack	= No
		AvailableAtStart			= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End



AddModule                       ; for special AI                 ; he fires this constantly to areas where creeps exit to prevent lag ( he kills creeps that left map)
  	Behavior = OCLSpecialPower ModuleTag_RainOfFire
		SpecialPowerTemplate = SpellBookRainOfFire
		OCL                  = OCL_SpellBookRainOfFire
		CreateLocation       = CREATE_AT_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = PlayerHealSpecialPower ModuleTag_Rebuild
		SpecialPowerTemplate = SpellBookRebuild
		HealAffects			 = STRUCTURE
		HealAsPercent		 	 = No
		HealAmount			 = 20000
		HealRadius			 = SPELL_REBUILD_RADIUS_STRUCTURE_SCAN
		HealFX				 = FX_SpellRebuild
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = SpecialPowerModule	SpellBookRebuild_ModuleTag2
		SpecialPowerTemplate		= SpellBookRebuild
		AttributeModifier			= SpellBookBuildingHeal
		AttributeModifierRange		= 200 ;75
		AttributeModifierAffects	= ANY +STRUCTURE
		TriggerFX					= FX_Industry
		UpdateModuleStartsAttack	= No
		AvailableAtStart			= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
 	Behavior   = SpecialPowerModule ModuleTag_Snowbind
		SpecialPowerTemplate		= SpellBookSnowbind
		AttributeModifier		= SpellBookSnowbind
		AttributeModifierRange		= SNOWBIND_EFFECT_RADIUS
		AttributeModifierAffects	= ANY ENEMIES ALLIES +STRUCTURE
		TriggerFX			= FX_SnowbindSpellFX
		UpdateModuleStartsAttack	= No
		AvailableAtStart		= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
		;TargetEnemy 		= Yes	//This is VERY important because it defaults to false and overrides the AttributeModifier filter above!!!
		TargetAllSides = Yes
	End
End 

AddModule
	Behavior = OCLSpecialPower ModuleTag_SummonDead
		SpecialPowerTemplate = SpellBookArmyoftheDead
		OCL                  = OCL_GondorArmyofTheDeadEgg
		TriggerFX			 = FX_SummonAOD
		CreateLocation		 = CREATE_AT_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = OCLSpecialPower ModuleTag_Flood
		SpecialPowerTemplate = SpellBookFlood
		OCL                  = OCL_SpellBookFlood
		CreateLocation       = CREATE_AT_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = OCLSpecialPower ModuleTag_SummonBalrog
		SpecialPowerTemplate = SpellBookBalrogAlly
		OCL                  = OCL_BalrogSummoning
		CreateLocation       = CREATE_AT_LOCATION
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule ModuleTag_Heal ;; added just in case it fully heals now
  	Behavior = PlayerHealSpecialPower ModuleTag_Heal
		SpecialPowerTemplate  = SpellBookHeal
		HealAffects			  = INFANTRY CAVALRY SHIP DOZER 
		HealAmount			  = 1.0 
		HealRadius			  = SPELL_HEAL_RADIUS_UNIT_SCAN	
		HealOCL               = OCL_HealSpellHordeReplenishPing
		AvailableAtStart	  = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
END

AddModule ModuleTag_ElvenGifts_Override
	Behavior = PlayerUpgradeSpecialPower	SpellBookElvenGifts_ModuleTag
		SpecialPowerTemplate		= SpellBookElvenGifts
		UpgradeName 				= Upgrade_ElvenGift
		UpdateModuleStartsAttack	= No
		AffectAllies				= Yes ; Should not try to affect ally units
		AvailableAtStart			= Yes
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
	End	


   AddModule 
	Behavior = SpecialPowerModule		ModuleTag_Fury
		SpecialPowerTemplate		= SpellBookFury
		UpdateModuleStartsAttack	= No
		AttributeModifier			= FuryBonus
		AttributeModifierRange		= 99999999.0 ; basically on the whole map
		AttributeModifierAffects	= ANY +INFANTRY +CAVALRY +MACHINE -IMMOBILE -DOZER +HERO -STRUCTURE -BASE_FOUNDATION -HORDE +DwarvenBattleWagon -RohanOathbreaker -MordorRamCrew +MordorWorker -IsengardRamCrew +IsengardBeserker
		AffectAllies			= No; Should not try to affect ally units
		AvailableAtStart		= No
		RequirementsFilterMPSkirmish	= SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic	= SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
   End



AddModule
	Behavior = OCLSpecialPower ModuleTag_Bombard
		SpecialPowerTemplate = SpellBookEvilBombard
		OCL                  = OCL_SpellBookBombardSeed
		CreateLocation       = USE_SECONDARY_OBJECT_LOCATION
		NearestSecondaryObjectFilter = NONE SAME_PLAYER +CASTLE_KEEP 
		AvailableAtStart	 = No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
	Behavior = CloudBreakSpecialPower	ModuleTag_CloudBreak
		SpecialPowerTemplate			= SpellBookCloudBreak
    	SunbeamObject					= CloudBreakSunbeam
		ObjectSpacing					= 300
		AttributeModifierAffects		= ANY +INFANTRY +CAVALRY +MONSTER -HERO ENEMIES
		ReEnableAntiCategory			= Yes ; cancel negative effects on good guys
		AttributeModifierWeatherBased	= Yes			
		WeatherDuration					= SPELL_CLOUDBREAK_DURATION
		ChangeWeather					= SUNNY
		AvailableAtStart				= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule
 	Behavior   = DarknessSpecialPower ModuleTag_Darkness
		SpecialPowerTemplate			= SpellBookDarkness
		AttributeModifier				= SpellBookDarkness
		AttributeModifierAffects		= ANY +INFANTRY +CAVALRY +MONSTER -HERO -HORDE ALLIES
		AttributeModifierWeatherBased	= Yes			
		WeatherDuration					= 450000
		ChangeWeather					= CLOUDY
		AvailableAtStart				= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End

AddModule ModuleTag_ElvenWood_Override
	Behavior = ElvenWoodSpecialPower ModuleTag_ElvenWood
		SpecialPowerTemplate	= SpellBookElvenWood
		ElvenGroveObject		= ElvenGrove
		ElvenWoodRadius			= SPELLBOOK_TAINT_RADIUS
		ElvenWoodFX				= FX_ElvenWoodSpellFX
		ElvenWoodOCL			= OCL_ElvenWoodSeed
		AvailableAtStart		= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
        End


END

