
Object SummonedDragon
	
	ReplaceModule ModuleTag_Body
	Body = ActiveBody ModuleTag_Body1
		MaxHealth = 60000
	End
	End

	LocomotorSet
		Locomotor     = SummonedDragonLocomotor
		Condition     = SET_NORMAL
		Speed         = 60
	End

	RemoveModule ModuleTag_LifetimeUpdate

	ArmorSet
		Conditions      = None
		Armor           = NewSummonedDragonArmor
		DamageFX        = FellBeastDamageFX
	End
End

ChildObject SummonedDragonJH1 SummonedDragon

	RemoveModule ModuleTag_LifetimeUpdate

	ArmorSet
		Conditions      = None
		Armor           = NewSummonedDragonArmor
		DamageFX        = FellBeastDamageFX
	End
End

Object MordorBalrog
 
	RemoveModule ModuleTag_LifetimeUpdate

;	ReplaceModule ModuleTag_LifetimeUpdate
;	Behavior = LifetimeUpdate ModuleTag_Overider
;    		MinLifetime = 500000000
;    		MaxLifetime = 500000000
;  	End
; 	End
 
 ReplaceModule ModuleTag_02
  Body = ActiveBody ModuleTag_Overide
    MaxHealth = 19500
    MaxHealthDamaged = 11000
  End
 End
End


Object RohanOathbreakerHorde
RemoveModule ModuleTag_LifetimeUpdate

End

Object ElvenMirkwoodArcherHorde
BuildTime = 10
BuildCost = 700
End

Object RohanOathbreakersCavalry
RemoveModule ModuleTag_LifetimeUpdate
End


Object GondorArcherRange
BuildTime = 10
End

Object GondorRangerHorde
BuildTime = 10
End

Object ElvenBattleTower
   BuildTime = 30
   ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 20000
                End
	End

End

Object GondorSentryTower
BuildTime = 25
End

Object IsengardLurtz
BountyValue = 150
End

Object DwarvenDain
BountyValue = 222
End

Object ElvenHaldir
BountyValue = 222
End
;//////////////////////////////////////////////////////////////////////////////
;FILE: PlayerTemplate.ini (SYSTEM) ///////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////////////
ChildObject MordorMouthOfSauronCalvalry MordorMouthOfSauron


	LocomotorSet
		Locomotor = HeroHumanLocomotor
		Condition = SET_NORMAL 
		Speed     = NORMAL_GOOD_HERO_SPEED
	End

	LocomotorSet
		Locomotor = HeroHorseLocomotor
		Condition = SET_MOUNTED 
		Speed     = 108
	End
End
