WaterTransparency
ReflectionPlaneZ = 256.0;
ReflectionOn = Yes
End
;-------------------------------------------------
Object GondorTownsmanTorch
      RadarPriority = NOT_ON_RADAR
End
;------------------------------------------------------------------------------

;-------------------------------------------------
Object CINE_ParticleSysProxy

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule    ; ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01New
    DefaultModelConditionState
      Model = NONE
    End
    ModelConditionState = WORLD_BUILDER
            Model = locator
    End
  End
END

AddModule
Draw = W3DLightDraw ModuleTag_W3DLightDraw
    Ambient        = R:0 G:0 B:0        ;; Ambient Color...
    Diffuse        = R:255 G:180 B:0    ;; Diffusive Color...
    Radius        = 90            ;; Radius of Light.
    Intensity        = 1.8            ;; Intensity of light.
    FlickerAmplitude    = 0.5        ;; How strong it "flickers".
    FlickerFrequency    = 0.55        ;; How often it "flickers".
;    AttachToBoneInAnotherModule = Torch
End
END

  DisplayName      = OBJECT:Prop
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes
END
;------------------------------------------------------------------------------
Object CINE_ParticleSysProxy2

  KindOf          = IMMOBILE CAN_CAST_REFLECTIONS

AddModule    ; ReplaceModule ModuleTag_l01
  Draw = W3DScriptedModelDraw ModuleTag_01lNew
    DefaultModelConditionState
      Model = NONE
    End
    ModelConditionState = WORLD_BUILDER
            Model = locator
    End
  End
END

AddModule
Draw = W3DLightDraw ModuleTag_W3DLightDraw
    Ambient        = R:0 G:0 B:0        ;; Ambient Color...
    Diffuse        = R:20 G:180 B:20    ;; Diffusive Color...
    Radius        = 180            ;; Radius of Light.
    Intensity        = 1.8            ;; Intensity of light.
    FlickerAmplitude    = 0.5        ;; How strong it "flickers".
    FlickerFrequency    = 0.55        ;; How often it "flickers".
;    AttachToBoneInAnotherModule = Torch
End
END

  DisplayName      = OBJECT:Prop
 
  KindOf          = IMMOBILE
  Shadow          = NONE

AddModule
  Body            = ActiveBody ModuleTag_l03
    MaxHealth       = 99999.0
  End
END

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes
END
;------------------------------------------------------------------------------
Object CINE_DeadGondorMan01

AddModule
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_new01
    DefaultModelConditionState
      Model = GUDeadTMN1
    End
  End

  ; ***DESIGN parameters ***
  DisplayName      = OBJECT:WeaponRack01
  EditorSorting   = MISC_MAN_MADE
  Browser = CINEMATICS MISC_MAN_MADE

  ; *** ENGINEERING Parameters ***  
  KindOf          = IMMOBILE
  Shadow          = NONE
  Body            = ActiveBody ModuleTag_new02
    MaxHealth       = 99999.0
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes
End
End

;------------------------------------------------------------------------------
Object CINE_DeadGondorMan02

AddModule
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_new03
    DefaultModelConditionState
      Model = GUDeadTMN2
    End
  End

  ; ***DESIGN parameters ***
  DisplayName      = OBJECT:WeaponRack01
  EditorSorting   = MISC_MAN_MADE
  Browser = CINEMATICS MISC_MAN_MADE

  ; *** ENGINEERING Parameters ***  
  KindOf          = IMMOBILE
  Shadow          = NONE
  Body            = ActiveBody ModuleTag_new04
    MaxHealth       = 99999.0
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes
End
End
;------------------------------------------------------------------------------
Object CINE_DeadGondorWoman01

AddModule
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_new05
    DefaultModelConditionState
      Model = GUDeadTWM1
    End
  End

  ; ***DESIGN parameters ***
  DisplayName      = OBJECT:WeaponRack01
  EditorSorting   = MISC_MAN_MADE
  Browser = CINEMATICS MISC_MAN_MADE

  ; *** ENGINEERING Parameters ***  
  KindOf          = IMMOBILE
  Shadow          = NONE
  Body            = ActiveBody ModuleTag_new06
    MaxHealth       = 99999.0
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes
End
End
;------------------------------------------------------------------------------
Object CINE_DeadGondorWoman02

AddModule
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_new07
    DefaultModelConditionState
      Model = GUDeadTWM2
    End
  End

  ; ***DESIGN parameters ***
  DisplayName      = OBJECT:WeaponRack01
  EditorSorting   = MISC_MAN_MADE
  Browser = CINEMATICS MISC_MAN_MADE

  ; *** ENGINEERING Parameters ***  
  KindOf          = IMMOBILE
  Shadow          = NONE
  Body            = ActiveBody ModuleTag_new08
    MaxHealth       = 99999.0
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 0.8
  GeometryMinorRadius = 0.8
  GeometryHeight = 0.8
  GeometryIsSmall = Yes
End
End

Object WatcherHittingArm
RemoveModule ModuleTag_LifetimeUpdate
End

Object IsengardMurderOfCrows
RemoveModule ModuleTag_LifetimeUpdate
End

Object WildBatCloud
RemoveModule ModuleTag_LifetimeUpdate
End

