Object WatcherHead
	RemoveModule ModuleTag_LifetimeUpdate
ReplaceModule ModuleTag_Body
	Body = ActiveBody ModuleTag_Overide
		MaxHealth = 15000
		End
	End
End

Object WatcherHittingArm	
	RemoveModule ModuleTag_LifetimeUpdate
End


Object WatcherCaldera
	RemoveModule ModuleTag_LifetimeUpdate
End

Object Wyrm
	RemoveModule ModuleTag_LifetimeUpdate
ReplaceModule ModuleTag_Body
	Body = ActiveBody ModuleTag_Overide
		MaxHealth = 20000
		End
	End
End

Armor NewSummonedDragonArmor
  Armor = DEFAULT		50%      ;this sets the level for all nonspecified damage types
  Armor = CRUSH			150%     ;horseman damage
  Armor = SLASH			250%     ;soldier damage
  Armor = URUK			250%     ;soldier damage
  Armor = PIERCE		90%      ;archer damage - has to be low because he is such an easy target
  Armor = SIEGE			55%      ;siege damage
  Armor = STRUCTURAL		55%	 ;Structural damage (Ent rocks)
  Armor = HERO			450%     ;hero damage
  Armor = MAGIC			250%     ;magic damage; ; 100
  Armor = HERO_RANGED		400%     ;Hero bow damage
  Armor = FLAME			125%     ;fire damage
  Armor = LOGICAL_FIRE		40%
  Armor = SPECIALIST    	350%
End

Armor NewBalrogArmor
  Armor = DEFAULT		3%     ;this sets the level for all nonspecified damage types
  Armor = CRUSH			6%     ;horseman damage
  Armor = SLASH			6%     ;soldier damage
  Armor = URUK			6%     ;soldier damage
  Armor = PIERCE		3%     ;archer damage
  Armor = SIEGE			8%     ;siege damage
  Armor = STRUCTURAL		8%	;Structural damage (Ent rocks)
  Armor = HERO			100%    ;hero damage
  Armor = MAGIC			8%     ;magic damage
  Armor = HERO_RANGED		80%    ;Hero bow damage   
End

Object MordorBalrog
	RemoveModule ModuleTag_LifetimeUpdate
	ArmorSet
		Armor           = NewBalrogArmor
		DamageFX        = FellBeastDamageFX
	End
End

Object SummonedDragon
	LocomotorSet
		Locomotor     = SummonedDragonLocomotor
		Condition     = SET_NORMAL
		Speed         = 60
	End

	RemoveModule ModuleTag_LifetimeUpdate

	ArmorSet
		Conditions      = None
		Armor           = NewSummonedDragonArmor
		DamageFX        = FellBeastDamageFX
	End
End

Object GondorWell
   ReplaceModule ModuleTag_05
     Body = StructureBody ModuleTag_Overide
		MaxHealth				= 12000
                End
	End
End

;----------------------------------------------------


Object CreateAHero
	RemoveModule ModuleTag_ConvertEnemySpecialPower_L1
End

Object CreateAHero
	RemoveModule ModuleTag_ConvertEnemySpecialPower_L2
End

Object CreateAHero
	RemoveModule ModuleTag_CreateAHeroCoercePower_Level1
End

Object CreateAHero
	RemoveModule ModuleTag_CreateAHeroCoercePower_Level2
End

Object CreateAHero
	RemoveModule ModuleTag_CreateAHeroCoercePower_Level3
End

SpecialPower SpecialAbilityGloinSmash
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime			= 240000
	RadiusCursorRadius 		= GLOIN_SMASH_WEAPON_RADIUS
	Flags				= PATHABLE_ONLY
End

SpecialPower SpecialAbilityCreateAHeroEarthShaker_Level1
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime			= 120000
	PublicTimer			= No
End

SpecialPower SpecialAbilityCreateAHeroEarthShaker_Level2
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime			= 200000
	PublicTimer			= No
End

SpecialPower SpecialAbilityCreateAHeroEarthShaker_Level3
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime			= 300000
	PublicTimer			= No
End

SpecialPower SpecialAbilityCreateAHeroLeap_Level1
	Enum				= SPECIAL_GIMLI_LEAP
	ReloadTime			= 90000
	PublicTimer			= No
	RadiusCursorRadius		= 35.0
	Flags				= PATHABLE_ONLY
End

SpecialPower SpecialAbilityCreateAHeroLeap_Level2
	Enum				= SPECIAL_GIMLI_LEAP
	ReloadTime			= 140000
	PublicTimer			= No
	RadiusCursorRadius		= 35.0
	Flags				= PATHABLE_ONLY
End

SpecialPower SpecialPowerCreateAHeroSpawnTornado_Level2
	Enum				= SPECIAL_SPAWN_TORNADO
	ReloadTime			= 280000 ; in milliseconds
	PublicTimer			= No
	RadiusCursorRadius		= 70.0
	ViewObjectRange			= 200 // how far from hero the spell can be cast
End

SpecialPower SpecialPowerCreateAHeroSpawnTornado_Level3
	Enum				= SPECIAL_SPAWN_TORNADO
	ReloadTime			= 320000 ; in milliseconds
	PublicTimer			= No
	RadiusCursorRadius		= 70.0
	ViewObjectRange			= 200 // how far from hero the spell can be cast
End

SpecialPower SpecialAbilityCreateAHeroFireBomb_Level3
	Enum			= SPECIAL_AT_VISIBLE_OBJECT
	ReloadTime		= 150000 //  in milliseconds
	PublicTimer		= No
End


SpecialPower SpecialAbilityCreateAHeroFireBomb_Level4
	Enum			= SPECIAL_AT_VISIBLE_OBJECT
	ReloadTime		= 200000 //  in milliseconds
	PublicTimer		= No
End

SpecialPower SpecialAbilityCreateAHeroBerserkerRage_Level4
	Enum			=	SPECIAL_GENERAL_TARGETLESS
	ReloadTime		=	240000
End

SpecialPower SpecialAbilityCreateAHeroSoSSummonAllies_Level4
	Enum				 =	SPECIAL_SUMMON_ALLIES
	ReloadTime			 =	240000	 //	   in milliseconds
	PublicTimer			 =	No
	RadiusCursorRadius	 	 =	50.0  
	InitiateAtLocationSound	 	 = CaH_CallReinforcementsEvil
	Flags			 	 = LIMIT_DISTANCE NO_FORBIDDEN_OBJECTS
	MaxCastRange		 	 = 800
	ForbiddenObjectFilter		 = NO_SUMMON_ALLIES_NEAR_THESE
	ForbiddenObjectRange	 	 = 50.0
End

SpecialPower SpecialAbilityCreateAHeroOilFire_Level3
	Enum			=	SPECIAL_GENERAL_TARGETLESS
	ReloadTime		=	240000
	PublicTimer		=	No
End

SpecialPower SpecialAbilityBallLightning_L3
	Enum			 	=	SPECIAL_WOUND_ARROW
	ReloadTime		 	=	120000  // in	milliseconds
	PublicTimer			=	No
	RadiusCursorRadius		=	240.0
	ObjectFilter			=	ALL	-BASE_FOUNDATION -INERT	-IGNORED_IN_GUI	-WALK_ON_TOP_OF_WALL -BLOCKING_GATE	-WALL_UPGRADE -UNATTACKABLE	-MOVE_ONLY
	InitiateAtLocationSound		= CaH_BallLightning
End

SpecialPower SpecialAbilityLightBlast_L3
	Enum				  =	SPECIAL_WOUND_ARROW
	ReloadTime			  =	150000 // in milliseconds
	PublicTimer			  =	No
	RadiusCursorRadius		  =	120.0
	ObjectFilter			  =	ALL	-BASE_FOUNDATION -INERT	-IGNORED_IN_GUI	-WALK_ON_TOP_OF_WALL -BLOCKING_GATE	-WALL_UPGRADE -UNATTACKABLE	-MOVE_ONLY
End

SpecialPower SpecialAbilityForcePush_Level3 // Based on Gandalf's Wizard blast
	Enum				  =	SPECIAL_WIZARD_BLAST
	ReloadTime			  =	90000
	PublicTimer			  =	No
End

SpecialPower SpecialAbilityCreateAHeroHeroicCharge
  Enum				  	= SPECIAL_TRIGGER_ATTRIBUTE_MODIFIER
  ReloadTime			  	= 360000 ; in milliseconds
  InitiateAtLocationSound		= GondorSoldierCelebratingLarge
  ;PalantirMovie			= PalantirAlert_RohanReinforcements
End

SpecialPower SpecialAbilityCreateAHeroStarlight
	Enum				= SPECIAL_GENERAL_TARGETLESS_THREE
	ReloadTime			= 260000
End

SpecialPower SuperweaponSpawnOathbreakers
	Enum				= SPECIAL_SPAWN_OATHBREAKERS
	ReloadTime			= 360000 ; ;180000	  ;	in milliseconds
	RadiusCursorRadius		= 60.0  
	Flags				= LIMIT_DISTANCE NO_FORBIDDEN_OBJECTS
	MaxCastRange			= 200
	ForbiddenObjectFilter		= NO_SUMMON_NEAR_OBJECT_FILTER
	ForbiddenObjectRange		= 60.0
	InitiateAtLocationSound		= AragornVoiceSummonOathbreakersMS
End

SpecialPower SpecialAbilityHornOfGondor
	Enum			= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 300000 ; ;60000
End

SpecialPower SpecialAbilityAragornElendil
	Enum			= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 240000
	InitiateSound		= AragornElendilEffect		   ;GenericSpell
End

SpecialPower SpecialAbilityBalrogBreath
	Enum			= SPECIAL_BALROG_BREATH
	ReloadTime		= 10000 ;20000
	RadiusCursorRadius = BALROG_BREATH_RADIUS
End

SpecialPower SpellBookRebuild
	Enum			= SPECIAL_SPELL_BOOK_REBUILD
	Flags			= WATER_OK RESPECT_RECHARGE_TIME_DISCOUNT
	ReloadTime		= 360000 ; ;SPELL_RECHARGE_TIME_TIER_2
	RadiusCursorRadius	= SPELL_REBUILD_RADIUS_CURSOR
	RequiredSciences	= SCIENCE_Rebuild
	InitiateAtLocationSound = SpellRebuild
; ;
	ObjectFilter		= NONE +STRUCTURE ALLIES ; ; INDUSTRY_TYPE_SPELL_OBJECT_FILTER 
End

;----------------------------------------------------

Object IsengardBallista
CommandPoints = 60
BuildTime = 200
MaxSimultaneousOfType = 2
End

Object GondorTrebuchet
CommandPoints = 60
BuildTime = 200
MaxSimultaneousOfType = 2
End

Object MordorCatapult
CommandPoints = 60
BuildCost = 800
BuildTime = 240
MaxSimultaneousOfType = 2
End

Object DwarvenCatapult
CommandPoints = 60
BuildTime = 200
MaxSimultaneousOfType = 2
End

;----------------------------------------------------

Object ElvenBattleTower
BuildCost = 200
BuildTime = 30
End

Object GondorBattleTower
BuildCost = 200
BuildTime = 30
End

Object DwarvenSentryTower
BuildCost = 200
BuildTime = 30
End

Object IsengardBattleTower
BuildCost = 200
BuildTime = 30
End

Object MordorBattleTower
BuildCost = 200
BuildTime = 15
End

Object WildSentryTower
BuildCost = 200
BuildTime = 20
End

Object AngmarSentryTower
BuildCost = 200
BuildTime = 20
End

;----------------------------------------------------

Object RohanElvenWarriorHorde
BuildTime = 20
BuildCost = 500
MaxSimultaneousOfType = 6
End

Object RohanHobbitFriendsHordeInn
BuildTime = 15
BuildCost = 150
MaxSimultaneousOfType = 8
End

Object RohanPeasantHorde
BuildTime = 10
BuildCost = 50
MaxSimultaneousOfType = 10
End

Object MordorHaradrimLancerHorde
BuildTime = 10
BuildCost = 50
MaxSimultaneousOfType = 10
End

Object GoblinsWildmanHordeInn
BuildTime = 25
BuildCost = 300
MaxSimultaneousOfType = 8
End

Object IsengardCorsairsOfUmbarHordeInn
BuildTime = 200
BuildCost = 800
MaxSimultaneousOfType = 2
End

;----------------------------------------------------

Object MordorCorsairsOfUmbarHorde
BuildTime = 200
BuildCost = 800
MaxSimultaneousOfType = 2
End

Object MordorOrcPit
BuildTime = 20
BuildCost = 100
End

Object MordorFighterHorde
BuildTime = 15
End

Object MordorArcherHorde
BuildTime = 20
BuildCost = 100
End

Object HaradrimPalace
BuildTime = 20
BuildCost = 200
End

Object MordorEasterlingHorde
BuildTime = 20
BuildCost = 250
End

Object MordorHaradrimArcherHorde
BuildTime = 15
BuildCost = 200
End

Object MordorMumakil
BuildCost = 600
End

Object MordorTavern
BuildCost = 300
End

Object MordorTrollCage
BuildCost = 300
End

Object MordorMumakilPen
BuildCost = 400
End

;----------------------------------------------------

Object DwarvenSiegeWorks
BuildCost = 500
BuildTime = 20
End

Object DwarvenArcheryRange
BuildCost = 350
End

Object DwarvenMenOfDaleHorde
BuildCost = 250
BuildTime = 40
End

Object DwarvenAxeThrowerHorde
BuildCost = 250
BuildTime = 25
End

Object DwarvenPhalanxHorde
BuildCost = 300
BuildTime = 25
End

Object DwarvenGuardianHorde
BuildCost = 300
End

;----------------------------------------------------

Object ElvenMithlondSentryHorde
BuildCost = 200
BuildTime = 20
End

Object ElvenLorienWarriorHorde
BuildCost = 300
BuildTime = 30
End

Object EregionForge
BuildCost = 750
End

;----------------------------------------------------

Object GoblinFissure
BuildTime = 40
BuildCost = 750
End

Object WildTreasureTrove
BuildCost = 750
BuildTime = 20
End

Object WildMarauderHorde
BuildCost = 300
BuildTime = 15
End

Object GoblinCave
BuildCost = 300
BuildTime = 20
End

Object GoblinArcherHorde
BuildCost = 80
BuildTime = 20
End

Object GoblinFighterHorde
BuildCost = 60
BuildTime = 15
End

Object WildSpiderPit
BuildCost = 300
BuildTime = 20
End

Object WildSpiderlingHorde
BuildCost = 200
BuildTime = 15
End

Object GoblinSpiderRiderHorde
BuildCost = 400
End

;----------------------------------------------------

Object GondorBarracks
BuildCost = 350
BuildTime = 20
End

Object GondorRangerHorde
BuildCost = 500
End

Object GondorTowerShieldGuardHorde
BuildCost = 400
End

Object GondorFighterHorde
BuildCost = 250
End

;----------------------------------------------------

Object IsengardPikemanHorde
BuildTime = 20
End

;----------------------------------------------------

Object AngmarBarracks
BuildCost = 300
BuildTime = 20
End

Object AngmarDen
BuildCost = 300
BuildTime = 20
End

Object AngmarHillTrollHorde
BuildCost = 400
BuildTime = 20
End



;----------------------------------------------------

